//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.ChamiloWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChamiloUser", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ChamiloUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LasttNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Registration_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sbyte StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LasttName {
            get {
                return this.LasttNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LasttNameField, value) != true)) {
                    this.LasttNameField = value;
                    this.RaisePropertyChanged("LasttName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Registration_date {
            get {
                return this.Registration_dateField;
            }
            set {
                if ((this.Registration_dateField.Equals(value) != true)) {
                    this.Registration_dateField = value;
                    this.RaisePropertyChanged("Registration_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sbyte Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="chamiloCource", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class chamiloCource : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string creation_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string directoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string expiration_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string last_editField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string last_visitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string creation_date {
            get {
                return this.creation_dateField;
            }
            set {
                if ((object.ReferenceEquals(this.creation_dateField, value) != true)) {
                    this.creation_dateField = value;
                    this.RaisePropertyChanged("creation_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string directory {
            get {
                return this.directoryField;
            }
            set {
                if ((object.ReferenceEquals(this.directoryField, value) != true)) {
                    this.directoryField = value;
                    this.RaisePropertyChanged("directory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string expiration_date {
            get {
                return this.expiration_dateField;
            }
            set {
                if ((object.ReferenceEquals(this.expiration_dateField, value) != true)) {
                    this.expiration_dateField = value;
                    this.RaisePropertyChanged("expiration_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string last_edit {
            get {
                return this.last_editField;
            }
            set {
                if ((object.ReferenceEquals(this.last_editField, value) != true)) {
                    this.last_editField = value;
                    this.RaisePropertyChanged("last_edit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string last_visit {
            get {
                return this.last_visitField;
            }
            set {
                if ((object.ReferenceEquals(this.last_visitField, value) != true)) {
                    this.last_visitField = value;
                    this.RaisePropertyChanged("last_visit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/")]
    public enum Role : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Profesor = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Estudiante = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invitado = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChamiloLesson", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ChamiloLesson : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int c_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private uint idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int c_id {
            get {
                return this.c_idField;
            }
            set {
                if ((this.c_idField.Equals(value) != true)) {
                    this.c_idField = value;
                    this.RaisePropertyChanged("c_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="chamiloDescriptionCatalog", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class chamiloDescriptionCatalog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string creation_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string name_completeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string creation_date {
            get {
                return this.creation_dateField;
            }
            set {
                if ((object.ReferenceEquals(this.creation_dateField, value) != true)) {
                    this.creation_dateField = value;
                    this.RaisePropertyChanged("creation_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name_complete {
            get {
                return this.name_completeField;
            }
            set {
                if ((object.ReferenceEquals(this.name_completeField, value) != true)) {
                    this.name_completeField = value;
                    this.RaisePropertyChanged("name_complete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChamiloWS.Ichamilo")]
    public interface Ichamilo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichamilo/insertUser", ReplyAction="http://tempuri.org/Ichamilo/insertUserResponse")]
        string insertUser(INI.ChamiloWS.ChamiloUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichamilo/insertUser", ReplyAction="http://tempuri.org/Ichamilo/insertUserResponse")]
        System.Threading.Tasks.Task<string> insertUserAsync(INI.ChamiloWS.ChamiloUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichamilo/deleteUser", ReplyAction="http://tempuri.org/Ichamilo/deleteUserResponse")]
        string deleteUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichamilo/deleteUser", ReplyAction="http://tempuri.org/Ichamilo/deleteUserResponse")]
        System.Threading.Tasks.Task<string> deleteUserAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichamilo/updateUser", ReplyAction="http://tempuri.org/Ichamilo/updateUserResponse")]
        string updateUser(INI.ChamiloWS.ChamiloUser user, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichamilo/updateUser", ReplyAction="http://tempuri.org/Ichamilo/updateUserResponse")]
        System.Threading.Tasks.Task<string> updateUserAsync(INI.ChamiloWS.ChamiloUser user, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichamilo/getUserChamilo", ReplyAction="http://tempuri.org/Ichamilo/getUserChamiloResponse")]
        INI.ChamiloWS.ChamiloUser getUserChamilo(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichamilo/getUserChamilo", ReplyAction="http://tempuri.org/Ichamilo/getUserChamiloResponse")]
        System.Threading.Tasks.Task<INI.ChamiloWS.ChamiloUser> getUserChamiloAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichamilo/getAllCources", ReplyAction="http://tempuri.org/Ichamilo/getAllCourcesResponse")]
        INI.ChamiloWS.chamiloCource[] getAllCources();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichamilo/getAllCources", ReplyAction="http://tempuri.org/Ichamilo/getAllCourcesResponse")]
        System.Threading.Tasks.Task<INI.ChamiloWS.chamiloCource[]> getAllCourcesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichamilo/getCourcesByUser", ReplyAction="http://tempuri.org/Ichamilo/getCourcesByUserResponse")]
        INI.ChamiloWS.chamiloCource[] getCourcesByUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichamilo/getCourcesByUser", ReplyAction="http://tempuri.org/Ichamilo/getCourcesByUserResponse")]
        System.Threading.Tasks.Task<INI.ChamiloWS.chamiloCource[]> getCourcesByUserAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichamilo/getCourceByRole", ReplyAction="http://tempuri.org/Ichamilo/getCourceByRoleResponse")]
        string[] getCourceByRole(INI.ChamiloWS.Role role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichamilo/getCourceByRole", ReplyAction="http://tempuri.org/Ichamilo/getCourceByRoleResponse")]
        System.Threading.Tasks.Task<string[]> getCourceByRoleAsync(INI.ChamiloWS.Role role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichamilo/getLessonByCource", ReplyAction="http://tempuri.org/Ichamilo/getLessonByCourceResponse")]
        INI.ChamiloWS.ChamiloLesson[] getLessonByCource(string cource);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichamilo/getLessonByCource", ReplyAction="http://tempuri.org/Ichamilo/getLessonByCourceResponse")]
        System.Threading.Tasks.Task<INI.ChamiloWS.ChamiloLesson[]> getLessonByCourceAsync(string cource);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichamilo/getTutorCource", ReplyAction="http://tempuri.org/Ichamilo/getTutorCourceResponse")]
        INI.ChamiloWS.chamiloDescriptionCatalog getTutorCource(string cource);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichamilo/getTutorCource", ReplyAction="http://tempuri.org/Ichamilo/getTutorCourceResponse")]
        System.Threading.Tasks.Task<INI.ChamiloWS.chamiloDescriptionCatalog> getTutorCourceAsync(string cource);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IchamiloChannel : INI.ChamiloWS.Ichamilo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IchamiloClient : System.ServiceModel.ClientBase<INI.ChamiloWS.Ichamilo>, INI.ChamiloWS.Ichamilo {
        
        public IchamiloClient() {
        }
        
        public IchamiloClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IchamiloClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IchamiloClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IchamiloClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string insertUser(INI.ChamiloWS.ChamiloUser user) {
            return base.Channel.insertUser(user);
        }
        
        public System.Threading.Tasks.Task<string> insertUserAsync(INI.ChamiloWS.ChamiloUser user) {
            return base.Channel.insertUserAsync(user);
        }
        
        public string deleteUser(string username) {
            return base.Channel.deleteUser(username);
        }
        
        public System.Threading.Tasks.Task<string> deleteUserAsync(string username) {
            return base.Channel.deleteUserAsync(username);
        }
        
        public string updateUser(INI.ChamiloWS.ChamiloUser user, string username) {
            return base.Channel.updateUser(user, username);
        }
        
        public System.Threading.Tasks.Task<string> updateUserAsync(INI.ChamiloWS.ChamiloUser user, string username) {
            return base.Channel.updateUserAsync(user, username);
        }
        
        public INI.ChamiloWS.ChamiloUser getUserChamilo(string username) {
            return base.Channel.getUserChamilo(username);
        }
        
        public System.Threading.Tasks.Task<INI.ChamiloWS.ChamiloUser> getUserChamiloAsync(string username) {
            return base.Channel.getUserChamiloAsync(username);
        }
        
        public INI.ChamiloWS.chamiloCource[] getAllCources() {
            return base.Channel.getAllCources();
        }
        
        public System.Threading.Tasks.Task<INI.ChamiloWS.chamiloCource[]> getAllCourcesAsync() {
            return base.Channel.getAllCourcesAsync();
        }
        
        public INI.ChamiloWS.chamiloCource[] getCourcesByUser(string username) {
            return base.Channel.getCourcesByUser(username);
        }
        
        public System.Threading.Tasks.Task<INI.ChamiloWS.chamiloCource[]> getCourcesByUserAsync(string username) {
            return base.Channel.getCourcesByUserAsync(username);
        }
        
        public string[] getCourceByRole(INI.ChamiloWS.Role role) {
            return base.Channel.getCourceByRole(role);
        }
        
        public System.Threading.Tasks.Task<string[]> getCourceByRoleAsync(INI.ChamiloWS.Role role) {
            return base.Channel.getCourceByRoleAsync(role);
        }
        
        public INI.ChamiloWS.ChamiloLesson[] getLessonByCource(string cource) {
            return base.Channel.getLessonByCource(cource);
        }
        
        public System.Threading.Tasks.Task<INI.ChamiloWS.ChamiloLesson[]> getLessonByCourceAsync(string cource) {
            return base.Channel.getLessonByCourceAsync(cource);
        }
        
        public INI.ChamiloWS.chamiloDescriptionCatalog getTutorCource(string cource) {
            return base.Channel.getTutorCource(cource);
        }
        
        public System.Threading.Tasks.Task<INI.ChamiloWS.chamiloDescriptionCatalog> getTutorCourceAsync(string cource) {
            return base.Channel.getTutorCourceAsync(cource);
        }
    }
}
