//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class AspNetRoles
    {
        public AspNetRoles()
        {
            this.AspNetUserRoles = new HashSet<AspNetUserRoles>();
        }
    
        [Display(Name="Id")]
        //[Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]
        //[RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Id")]
        //[StringLength(128, ErrorMessage = "Máximo 128 caracteres")]
        public string Id { get; set; }
		
        [Display(Name="Nombre")]
        //[Required(AllowEmptyStrings = false, ErrorMessage = "El Nombre es obligatorio")]
        //[RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Nombre")]
        //[StringLength(256, ErrorMessage = "Máximo 256 caracteres")]

        public string Name { get; set; }
		
    
        public virtual ICollection<AspNetUserRoles> AspNetUserRoles { get; set; }
    }
}
