//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class AspNetUserRoles
    {
        [Display(Name="Id")]
        //[Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]
        //[RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Id")]
        //[StringLength(128, ErrorMessage = "Máximo 128 caracteres")]
        [Range(0,int.MaxValue)]
		public int Id { get; set; }
		
        [Display(Name="User Id")]
        //[Required(AllowEmptyStrings = false, ErrorMessage = "El User Id es obligatorio")]
        //[RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para User Id")]
        //[StringLength(128, ErrorMessage = "Máximo 128 caracteres")]
        public string UserId { get; set; }
		
        [Display(Name="Role Id")]
        //[Required(AllowEmptyStrings = false, ErrorMessage = "El Role Id es obligatorio")]
        //[RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Role Id")]
        //[StringLength(128, ErrorMessage = "Máximo 128 caracteres")]
        public string RoleId { get; set; }
		
    
        public virtual AspNetRoles AspNetRoles { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
