//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class AspNetUserLogins
    {
        [Display(Name="Login Provider")]
        [Required]

        public string LoginProvider { get; set; }
		
        [Display(Name="Provider Key")]
        [Required]
        public string ProviderKey { get; set; }
		
        [Display(Name="UserId")]
        [Required]

        public string UserId { get; set; }
		
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
