//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_course_setting
    {
        public int c_id { get; set; }
        public long id { get; set; }
        public string variable { get; set; }
        public string subkey { get; set; }
        public string type { get; set; }
        public string category { get; set; }
        public string value { get; set; }
        public string title { get; set; }
        public string comment { get; set; }
        public string subkeytext { get; set; }
    }
}
