//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class c_course_description
    {
        public int c_id { get; set; }
        public long id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public Nullable<int> session_id { get; set; }
        public byte description_type { get; set; }
        public int progress { get; set; }
    }
}
