//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class CategoriaRepositorio
    {
        public CategoriaRepositorio()
        {
            this.SubCategoriaRepositorio = new HashSet<SubCategoriaRepositorio>();
        }
    
        [Display(Name="Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]
        [RegularExpression(@"^[0-9 ]+$", ErrorMessage = "Carácter no valido para Id")]
        [Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name="Nombre")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Nombre es obligatorio")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Nombre")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]
        public string nombre { get; set; }
		
        [Display(Name="Url img")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Url img es obligatoria")]
        public string urlimg { get; set; }
		
    
        public virtual ICollection<SubCategoriaRepositorio> SubCategoriaRepositorio { get; set; }
    }
}
