//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class chamiloEntities : DbContext
    {
        public chamiloEntities()
            : base("name=chamiloEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<c_course_description> c_course_description { get; set; }
        public virtual DbSet<c_course_setting> c_course_setting { get; set; }
        public virtual DbSet<course> course { get; set; }
        public virtual DbSet<course_category> course_category { get; set; }
        public virtual DbSet<course_field> course_field { get; set; }
        public virtual DbSet<course_field_values> course_field_values { get; set; }
        public virtual DbSet<course_module> course_module { get; set; }
        public virtual DbSet<course_rel_class> course_rel_class { get; set; }
        public virtual DbSet<course_rel_user> course_rel_user { get; set; }
        public virtual DbSet<course_request> course_request { get; set; }
        public virtual DbSet<course_type> course_type { get; set; }
    }
}
