//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class course_category
    {
        public long id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string parent_id { get; set; }
        public Nullable<long> tree_pos { get; set; }
        public Nullable<short> children_count { get; set; }
        public string auth_course_child { get; set; }
        public string auth_cat_child { get; set; }
    }
}
