//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class course_field
    {
        public int id { get; set; }
        public int field_type { get; set; }
        public string field_variable { get; set; }
        public string field_display_text { get; set; }
        public string field_default_value { get; set; }
        public Nullable<int> field_order { get; set; }
        public Nullable<sbyte> field_visible { get; set; }
        public Nullable<sbyte> field_changeable { get; set; }
        public Nullable<sbyte> field_filter { get; set; }
        public System.DateTime tms { get; set; }
    }
}
