//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class course_request
    {
        public int id { get; set; }
        public string code { get; set; }
        public long user_id { get; set; }
        public string directory { get; set; }
        public string db_name { get; set; }
        public string course_language { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string category_code { get; set; }
        public string tutor_name { get; set; }
        public string visual_code { get; set; }
        public System.DateTime request_date { get; set; }
        public string objetives { get; set; }
        public string target_audience { get; set; }
        public long status { get; set; }
        public long info { get; set; }
        public long exemplary_content { get; set; }
    }
}
