//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class Revista
    {
        [Display(Name="id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]
        [RegularExpression(@"^[0-9 ]+$", ErrorMessage = "Carácter no valido para Id")]
        [Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name= "Título")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Título es obligatorio")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Título")]
        [StringLength(100, ErrorMessage = "Máximo 100 caracteres")]
        public string title { get; set; }
		
        [Display(Name="Url Pdf")]
        public string urlPdf { get; set; }
		
        [Display(Name="Sub Categoria Id")]
		[Range(0,int.MaxValue)]
		public Nullable<int> id_SubCategoria { get; set; }
		
        [Display(Name= "Descripción")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Título")]
        public string Description { get; set; }
		
        [Display(Name="Url Front")]
		public string urlfront { get; set; }
		
    
        public virtual SubCategoriaRevista SubCategoriaRevista { get; set; }
    }
}
