//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblAlternativas
    {
        public tblAlternativas()
        {
            this.tblActividadContratista = new HashSet<tblActividadContratista>();
            this.tblProgramaTareasContratista = new HashSet<tblProgramaTareasContratista>();
        }
    
        [Display(Name="Alternativa Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int Id_Alternativa { get; set; }
		
        [Display(Name="Des Alternativa")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Des Alternativa es obligatorio")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Des Alternativa")]
        public string Des_Alternativa { get; set; }
		
    
        public virtual ICollection<tblActividadContratista> tblActividadContratista { get; set; }
        public virtual ICollection<tblProgramaTareasContratista> tblProgramaTareasContratista { get; set; }
    }
}
