//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblAsesorZona
    {
        public tblAsesorZona()
        {
            this.tblAsesorZonaMunicipio = new HashSet<tblAsesorZonaMunicipio>();
        }
    
        [Display(Name="Asesor Zona ID")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Asesor Zona ID es obligatorio")]
        public long tblAsesorZona_ID { get; set; }
		
        [Display(Name= "Nombre Asesor Zona")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Nombre Asesor Zona es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Nombre Asesor Zona")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]

        public string aseZon_nombre { get; set; }
		
        [Display(Name= "Apellido Asesor Zona")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Apellido Asesor Zona es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Apellido Asesor Zona")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]
        public string aseZon_apellido { get; set; }
		
        [Display(Name= "Correo Asesor Zona")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Correo Asesor Zona es obligatorio")]
        [StringLength(255, ErrorMessage = "Máximo 255 caracteres")]
        public string aseZon_correo { get; set; }
		
        [Display(Name= "Teléfono Asesor Zona")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]
        public string aseZon_telefono { get; set; }
		
        [Display(Name="Equipo Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Equipo Id es obligatorio")]
        public long tblEquipo_ID { get; set; }
		
        [Display(Name="Municipio ID")]
        [StringLength(5, ErrorMessage = "Máximo 5 caracteres")]
        public string tblMunicipio_ID { get; set; }
		
        [Display(Name="Está Activo")]
		public Nullable<bool> estaActivo { get; set; }
		
    
        public virtual tblEquipo tblEquipo { get; set; }
        public virtual tblMunicipios tblMunicipios { get; set; }
        public virtual ICollection<tblAsesorZonaMunicipio> tblAsesorZonaMunicipio { get; set; }
    }
}
