//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblAsesorZonaMunicipio
    {
        [Display(Name= "Asesor Zona Municipio Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Asesor Zona Municipio Id es obligatorio")]
        public long tblAsMun_ID { get; set; }
		
        [Display(Name= "Asesor Zona Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Asesor Zona Id es obligatorio")]
        public long tblAsesorZona_ID { get; set; }
		
        [Display(Name= "Municipio Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Municipio Id es obligatorio")]
        public long tblMunicipio_ID { get; set; }
		
    
        public virtual tblAsesorZona tblAsesorZona { get; set; }
    }
}
