//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblActividadContratista
    {
        public tblActividadContratista()
        {
            this.tblEvidenciasContratista = new HashSet<tblEvidenciasContratista>();
            this.tblProductosContratista = new HashSet<tblProductosContratista>();
        }
    
        [Display(Name= "Actividad Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]
        [RegularExpression(@"^[0-9 ]+$", ErrorMessage = "Carácter no valido para Id")]
        [Range(0,int.MaxValue)]
		public int Id_Actividad { get; set; }
		
        [Display(Name="Fecha Inicio")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Fecha Inicio es obligatoria")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Fecha_Ini { get; set; }
		
        [Display(Name="Fecha Fin")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Fecha Fin es obligatoria")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Fecha_Fin { get; set; }
		
        [Display(Name="Contratista Id")]
        [StringLength(128, ErrorMessage = "Máximo 128 caracteres")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Contratista Id es obligatorio")]
        public string Id_Contratista { get; set; }
		
        [Display(Name= "Alternativa Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]
        [RegularExpression(@"^[0-9 ]+$", ErrorMessage = "Carácter no valido para Id")]
        [Range(0,int.MaxValue)]
		public int Id_Alternativa { get; set; }
		
        [Display(Name="Des_Resp_Contratista")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Des Resp Contratista es obligatorio")]
        [RegularExpression(@"^[0-9 ]+$", ErrorMessage = "Carácter no valido para Des Resp Contratista")]
        [Range(0,int.MaxValue)]
		public int Des_Resp_Contratista { get; set; }
		
        [Display(Name="Des Actividad")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Des Actividad es obligatorio")]
        public string Des_Actividad { get; set; }
		
        [Display(Name="Estado Id")]
        [RegularExpression(@"^[0-9 ]+$", ErrorMessage = "Carácter no valido para Estado Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Estado Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int Id_Estado { get; set; }
		
        [Display(Name="Des Observaciones")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string Des_Observaciones { get; set; }
		
        [Display(Name="Periodo_Reporte")]
        [RegularExpression(@"^[0-9 ]+$", ErrorMessage = "Carácter no valido para Periodo Reporte")]
        [Range(0,int.MaxValue)]
		public Nullable<int> Periodo_Reporte { get; set; }
		
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<tblEvidenciasContratista> tblEvidenciasContratista { get; set; }
        public virtual ICollection<tblProductosContratista> tblProductosContratista { get; set; }
        public virtual tblResponsabContratista tblResponsabContratista { get; set; }
        public virtual tblAlternativas tblAlternativas { get; set; }
        public virtual tblEstadoTarea tblEstadoTarea { get; set; }
    }
}
