//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblAsesor
    {
        public tblAsesor()
        {
            this.tblAsesorGrupoInvestigacion = new HashSet<tblAsesorGrupoInvestigacion>();
        }
    
        [Display(Name="id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name="User Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El User Id es obligatorio")]
        [StringLength(128, ErrorMessage = "Máximo 128 caracteres")]
        public string idUser { get; set; }
		
        [Display(Name="Está Activo")]
		public Nullable<bool> estaActivo { get; set; }
		
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<tblAsesorGrupoInvestigacion> tblAsesorGrupoInvestigacion { get; set; }
    }
}
