//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblBitacoraGrupoInvestigacion
    {
        [Display(Name="Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name= "Grupo Investigación Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int idGrupoInvestigacion { get; set; }
		
        [Display(Name="Título")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Título")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Título es obligatorio")]
        public string Titulo_1 { get; set; }
		
        [Display(Name="Nombre")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Nombre es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Nombre")]

        public string Nombre_1 { get; set; }
		
        [Display(Name="Maestro")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Maestro")]
        public string Maestro_1 { get; set; }
		
        [Display(Name= "Introducción")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string Introduccion_1 { get; set; }
		
        [Display(Name= "Resumen Final")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string ResumenFinal_1 { get; set; }
		
        [Display(Name= "Insignia Grupo URL")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string InsigniaGrupoURL_2 { get; set; }
		
        [Display(Name= "Pregunta Investigación")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string PreguntaInvestigacion_2 { get; set; }
		
        [Display(Name= "Descripción Problema")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string DescripcionProblema_2 { get; set; }
		
        [Display(Name="Objetivos")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string Objetivos_2 { get; set; }
		
        [Display(Name= "Actividades Realizadas")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string ActividadesRealizadas_2 { get; set; }
		
        [Display(Name= "Conceptos Principales")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string ConceptosPrincipales_3 { get; set; }
		
        [Display(Name= "Resultados")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string Resultalos_3 { get; set; }
		
        [Display(Name= "Participación 3")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string Participacion_3 { get; set; }
		
        [Display(Name= "Conclusiones 4")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string Concluciones_4 { get; set; }
		
        [Display(Name= "Bibliografía 5")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string Bibliografia_5 { get; set; }
		
        [Display(Name= "Ponencia 6")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string Ponencia_6 { get; set; }
		
    
        public virtual tblGrupoInvestigacion tblGrupoInvestigacion { get; set; }
    }
}
