//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblCronogramaProy_Rev
    {
        public tblCronogramaProy_Rev()
        {
            this.tblProyectosInvestigacion_Rev = new HashSet<tblProyectosInvestigacion_Rev>();
        }
    
        [Display(Name= "Cronograma Proyecto Revisión Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Cronograma Proyecto Revisión Id es obligatorio")]
        public long tblCronogramaProy_Rev_ID { get; set; }
		
        [Display(Name= "Cronograma Proyecto Revision")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string croProy_revision { get; set; }
		
    
        public virtual ICollection<tblProyectosInvestigacion_Rev> tblProyectosInvestigacion_Rev { get; set; }
    }
}
