//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblCoInvestigadorGrupoInvestigacion
    {
        [Display(Name="id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name="Usuario")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Usuario Id es obligatorio")]
        [StringLength(128, ErrorMessage = "Máximo 128 caracteres")]
        public string idUsuario { get; set; }
		
        [Display(Name= "Grupo Investigación")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Grupo Investigación Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int idGrupoInvestigacion { get; set; }
		
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tblGrupoInvestigacion tblGrupoInvestigacion { get; set; }
    }
}
