//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblColecciones
    {
        public tblColecciones()
        {
            this.tblRecursosEducativos = new HashSet<tblRecursosEducativos>();
        }
    
        [Display(Name= "Colección Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Colección Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int id_coleccion { get; set; }
		
        [Display(Name= "Colección Nombre")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Colección Nombre es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Colección Nombre")]
        [StringLength(100, ErrorMessage = "Máximo 100 caracteres")]

        public string nom_coleccion { get; set; }
		
        [Display(Name= "Colección Descripción")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Colección Descripción es obligatoria")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Colección Descripción")]
        [StringLength(100, ErrorMessage = "Máximo 100 caracteres")]
        public string desc_coleccion { get; set; }
		
    
        public virtual ICollection<tblRecursosEducativos> tblRecursosEducativos { get; set; }
    }
}
