//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblComentarioGrupo
    {
        [Display(Name="id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name="Grupo Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Grupo Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int idGrupo { get; set; }
		
        [Display(Name="User Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El User Id es obligatorio")]
        [StringLength(128, ErrorMessage = "Máximo 128 caracteres")]
        public string UserId { get; set; }
		
        [Display(Name="Comentario")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El comentario es obligatorio")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Comentario")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]

        public string Comentario { get; set; }
		
        [Display(Name="Aprobado")]
		public Nullable<bool> Aprobado { get; set; }
		
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tblGrupoInvestigacion tblGrupoInvestigacion { get; set; }
    }
}
