//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblCargos
    {
        [Display(Name="Cargo Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Cargo Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int Id_Cargo { get; set; }
		
        [Display(Name="Nombre Cargo")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Nombre Cargo es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Nombre Cargo")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string Nombre_Cargo { get; set; }
		
    }
}
