//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblCriticoSocial
    {
        public tblCriticoSocial()
        {
            this.tblMetodoProy = new HashSet<tblMetodoProy>();
        }
    
        [Display(Name= "Critico Social Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Critico Social Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int tblCriticoSocial_ID { get; set; }
		
        [Display(Name= "Critico Social Nombre")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Critico Social Nombre es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Critico Social Nombre")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]

        public string critSoc_nombre { get; set; }
		
    
        public virtual ICollection<tblMetodoProy> tblMetodoProy { get; set; }
    }
}
