//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblCategoriaProductos
    {
        public tblCategoriaProductos()
        {
            this.tblProductosAcademicos = new HashSet<tblProductosAcademicos>();
        }
    
        [Display(Name= "Categoría Productos Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Categoría Productos Id es obligatoria")]
        public long tblCategoriaProductos_ID { get; set; }
		
        [Display(Name= "Nombre  Categoría Productos")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Nombre  Categoría Productos es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Nombre Categoría Productos")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]
        public string catpro_nombre { get; set; }
		
    
        public virtual ICollection<tblProductosAcademicos> tblProductosAcademicos { get; set; }
    }
}
