//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblDocumentosSoporte
    {
        [Display(Name="Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name= "Carta Compromiso")]
        [StringLength(255, ErrorMessage = "Máximo 255 caracteres")]
        public string CartaCompromiso { get; set; }
		
        [Display(Name= "Carta Aceptación")]
        [StringLength(255, ErrorMessage = "Máximo 255 caracteres")]
        public string CartaAceptacion { get; set; }
		
        [Display(Name= "Grupo Investigación")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Grupo Investigación es obligatorio")]
        [Range(0,int.MaxValue)]
		public int idGrupoInvestigacion { get; set; }
    
        public virtual tblGrupoInvestigacion tblGrupoInvestigacion { get; set; }
    }
}
