//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblEventosAcademicos
    {
        [Display(Name= "Eventos Académicos Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Eventos Académicos Id es obligatorio")]
        public long tblEventosAcademicos_ID { get; set; }
		
        [Display(Name= "Eventos Académicos Tìtulo")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Eventos Académicos Tìtulo es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Eventos Académicos Tìtulo")]
        [StringLength(255, ErrorMessage = "Máximo 255 caracteres")]
        public string eveaca_tituloEvento { get; set; }
		
        [Display(Name= "Eventos Académicos Evento")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Eventos Académicos Evento es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Eventos Académicos Evento")]
        [StringLength(255, ErrorMessage = "Máximo 255 caracteres")]
        public string eveaca_evento { get; set; }
		
        [Display(Name= "Eventos Académicos Lugar")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Eventos Académicos Lugar es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Eventos Académicos Lugar")]
        [StringLength(255, ErrorMessage = "Máximo 255 caracteres")]
        public string eveaca_lugarEvento { get; set; }
		
        [Display(Name= "Eventos Académicos Ano Terminación")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> eveaca_anoTerminacion { get; set; }
		
        [Display(Name= "Hoja Vida Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Hoja Vida Id es obligatoria")]
        public long tblHojaVida_ID { get; set; }
		
    
        public virtual tblHojaVida tblHojaVida { get; set; }
    }
}
