//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblEquipo
    {
        public tblEquipo()
        {
            this.tblAsesorZona = new HashSet<tblAsesorZona>();
            this.tblIntegrante = new HashSet<tblIntegrante>();
        }
    
        [Display(Name="Equipo Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Equipo Id es obligatorio")]
        public long tblEquipo_ID { get; set; }
		
        [Display(Name= "Equipo Descripción")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Equipo Descripción es obligatorio")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string equ_descripcion { get; set; }
		
        [Display(Name= "Equipo Observación")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Equipo Observación es obligatorio")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string equ_Observacion { get; set; }
		
    
        public virtual ICollection<tblAsesorZona> tblAsesorZona { get; set; }
        public virtual ICollection<tblIntegrante> tblIntegrante { get; set; }
    }
}
