//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblEvidenciasContratista
    {
        [Display(Name= "Evidencias Contratista Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Evidencias Contratista Id es obligatoria")]
        [Range(0,int.MaxValue)]
		public int Id_Evidencia { get; set; }
		
        [Display(Name= "Contratista Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Contratista Id es obligatorio")]
        [StringLength(128, ErrorMessage = "Máximo 128 caracteres")]
        public string Id_Contratista { get; set; }
		
        [Display(Name= "Actividad Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Actividad Id es obligatoria")]
        [Range(0,int.MaxValue)]
		public int Id_Actividad { get; set; }
		
        [Display(Name= "Nombre Evidencia")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Nombre Evidencia es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Nombre Evidencia")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]

        public string Nombre_Evidencia { get; set; }
		
        [Display(Name= "Descripción Evidencia")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Descripción Evidencia es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Descripción Evidencia")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string Descripcion_Evidencia { get; set; }
		
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tblActividadContratista tblActividadContratista { get; set; }
    }
}
