//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblEjeInvestigacion
    {
        public tblEjeInvestigacion()
        {
            this.tblPresentacionProyecto = new HashSet<tblPresentacionProyecto>();
        }
    
        [Display(Name= "Ejes de Investigación ID")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Ejes de Investigación Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int tblEjeInvestigacion_ID { get; set; }
		
        [Display(Name= "Nombre Ejes de Investigación")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El ejes de Investigación es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para ejes de Investigación")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string ejeInv_nombre { get; set; }
		
    
        public virtual ICollection<tblPresentacionProyecto> tblPresentacionProyecto { get; set; }
    }
}
