//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblEstadoTarea
    {
        public tblEstadoTarea()
        {
            this.tblActividadContratista = new HashSet<tblActividadContratista>();
        }
    
        [Display(Name="Estado Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Estado Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int Id_Estado { get; set; }
		
        [Display(Name= "Descripción Estado")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Descripción Estado es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Descripción Estado")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]

        public string Des_Estado { get; set; }
		
    
        public virtual ICollection<tblActividadContratista> tblActividadContratista { get; set; }
    }
}
