//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblEstadoArteProyectoInvestigacion
    {
        public tblEstadoArteProyectoInvestigacion()
        {
            this.tblConceptosEstadoArte = new HashSet<tblConceptosEstadoArte>();
        }
    
        [Display(Name="id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name= "Grupo Investigación Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Grupo Investigación Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int idGrupoInvestigacion { get; set; }
		
        [Display(Name= "Tema Investigación")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Tema Investigación es obligatorio")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string TemaInvestigacion { get; set; }
		
        [Display(Name= "Mapa Conceptual")]
        [StringLength(255, ErrorMessage = "Máximo 255 caracteres")]
        public string MapaConceptual { get; set; }
		
    
        public virtual ICollection<tblConceptosEstadoArte> tblConceptosEstadoArte { get; set; }
        public virtual tblGrupoInvestigacion tblGrupoInvestigacion { get; set; }
    }
}
