//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblExperienciaProyectos
    {
        [Display(Name= "Experiencia Proyectos Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Experiencia Proyectos Id es obligatoria")]
        public long tblExperienciaProyectos_ID { get; set; }
		
        [Display(Name= "Experiencia Proyectos Título")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Experiencia Proyectos Título es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Experiencia Proyectos Título")]
        [StringLength(255, ErrorMessage = "Máximo 255 caracteres")]

        public string exppro_tituloProyecto { get; set; }
		
        [Display(Name= "Experiencia Proyectos Ano Terminación")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> exppro_anoTerminacion { get; set; }
		
        [Display(Name="Hoja Vida ID")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Hoja Vida ID es obligatoria")]
        public long tblHojaVida_ID { get; set; }
		
    
        public virtual tblHojaVida tblHojaVida { get; set; }
    }
}
