//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblGruposInvestigacion
    {
        public tblGruposInvestigacion()
        {
            this.tblIntegrantesGrupoInv = new HashSet<tblIntegrantesGrupoInv>();
            this.tblProyectosInvestigacion = new HashSet<tblProyectosInvestigacion>();
        }
    
        [Display(Name= "Grupos Investigación Id")]
        [Required]
        //[Required(AllowEmptyStrings = false, ErrorMessage = "El Grupos Investigación Id es obligatorio")]
        public long tblGruposInvestigacion_ID { get; set; }
		
        [Display(Name= "Usuario Plataforma Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Usuario Plataforma Id es obligatorio")]
        [StringLength(128, ErrorMessage = "Máximo 128 caracteres")]
        public string tblUsuarioPlataforma_ID { get; set; }
		
        [Display(Name= "Grupos Investigación Nombre")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Grupos Investigación Nombre es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido Grupos Investigación Nombre")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]

        public string gruInv_nombreGrupo { get; set; }
		
        [Display(Name= "Grupos Investigación Emblema")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string gruInv_emblema { get; set; }
		
        [Display(Name= "Estado Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Estado Id es obligatorio")]
        public long tblEstado_ID { get; set; }
		
        [Display(Name= "Grupos Investigación Fecha Creación")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Fecha Creación es obligatoria")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime gruInv_fechaCreacion { get; set; }
		
        [Display(Name= "Grupos Investigación Proyectos")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Grupos Investigación Proyectos es obligatorio")]
        [Range(0,int.MaxValue)]
		public int gruInv_proyectos { get; set; }
		
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tblEstado tblEstado { get; set; }
        public virtual ICollection<tblIntegrantesGrupoInv> tblIntegrantesGrupoInv { get; set; }
        public virtual ICollection<tblProyectosInvestigacion> tblProyectosInvestigacion { get; set; }
    }
}
