//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblGrupoInvestigacion
    {
        public tblGrupoInvestigacion()
        {
            this.tblBitacoraGrupoInvestigacion = new HashSet<tblBitacoraGrupoInvestigacion>();
            this.tblCoInvestigadorGrupoInvestigacion = new HashSet<tblCoInvestigadorGrupoInvestigacion>();
            this.tblComentarioGrupo = new HashSet<tblComentarioGrupo>();
            this.tblDocumentosSoporte = new HashSet<tblDocumentosSoporte>();
            this.tblEstadoArteProyectoInvestigacion = new HashSet<tblEstadoArteProyectoInvestigacion>();
            this.tblForoProyectoInvestigacion = new HashSet<tblForoProyectoInvestigacion>();
            this.tblInvitacionGrupo = new HashSet<tblInvitacionGrupo>();
            this.tblMiembroGrupo = new HashSet<tblMiembroGrupo>();
            this.tblPreguntaInvestigacion = new HashSet<tblPreguntaInvestigacion>();
            this.tblPreguntaProyectoInvestigacion = new HashSet<tblPreguntaProyectoInvestigacion>();
            this.tblPresupuestoProyectoInvestigacion = new HashSet<tblPresupuestoProyectoInvestigacion>();
            this.tblProblemaInvestigacion = new HashSet<tblProblemaInvestigacion>();
            this.tblProblemaProyectoInvestigacion = new HashSet<tblProblemaProyectoInvestigacion>();
            this.tblPropagacionGrupo = new HashSet<tblPropagacionGrupo>();
            this.tblProyectoInvestigacion = new HashSet<tblProyectoInvestigacion>();
            this.tblRecoleccionInformacionProyectoInvestigacion = new HashSet<tblRecoleccionInformacionProyectoInvestigacion>();
            this.tblReflexionOnda = new HashSet<tblReflexionOnda>();
            this.tblReflexionProyectoInvestigacion = new HashSet<tblReflexionProyectoInvestigacion>();
            this.tblSeguimientoProyectoInvestigacion = new HashSet<tblSeguimientoProyectoInvestigacion>();
        }
    
        [Display(Name="Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name= "Código")]
        [StringLength(10, ErrorMessage = "Máximo 10 caracteres")]
        public string Codigo { get; set; }
		
        [Display(Name="Nombre")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Nombre es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Nombre")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]

        public string Nombre { get; set; }
		
        [Display(Name= "Fecha Creación")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Fecha Creación es obligatoria")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime FechaCreacion { get; set; }
		
        [Display(Name="Tipo Grupo")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Tipo Grupo es obligatorio")]
        [Range(0,int.MaxValue)]
		public int TipoGrupo { get; set; }
		
        [Display(Name="Avatar")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]
        public string Avatar { get; set; }
		
        [Display(Name= "Institución Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Institución Id es obligatoria")]
        [Range(0,int.MaxValue)]
		public int idInstitucion { get; set; }
		
        [Display(Name= "Línea Investigación ID")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Línea Investigación Id es obligatoria")]
        [Range(0,int.MaxValue)]
		public int idLineaInvestigacion { get; set; }
		
        [Display(Name= "Usuario Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Usuario Id es obligatorio")]
        [StringLength(128, ErrorMessage = "Máximo 128 caracteres")]
        public string idUsuario { get; set; }
		
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<tblBitacoraGrupoInvestigacion> tblBitacoraGrupoInvestigacion { get; set; }
        public virtual ICollection<tblCoInvestigadorGrupoInvestigacion> tblCoInvestigadorGrupoInvestigacion { get; set; }
        public virtual ICollection<tblComentarioGrupo> tblComentarioGrupo { get; set; }
        public virtual ICollection<tblDocumentosSoporte> tblDocumentosSoporte { get; set; }
        public virtual ICollection<tblEstadoArteProyectoInvestigacion> tblEstadoArteProyectoInvestigacion { get; set; }
        public virtual ICollection<tblForoProyectoInvestigacion> tblForoProyectoInvestigacion { get; set; }
        public virtual tblInstitucion tblInstitucion { get; set; }
        public virtual tblLineaInvestigacion tblLineaInvestigacion { get; set; }
        public virtual ICollection<tblInvitacionGrupo> tblInvitacionGrupo { get; set; }
        public virtual ICollection<tblMiembroGrupo> tblMiembroGrupo { get; set; }
        public virtual ICollection<tblPreguntaInvestigacion> tblPreguntaInvestigacion { get; set; }
        public virtual ICollection<tblPreguntaProyectoInvestigacion> tblPreguntaProyectoInvestigacion { get; set; }
        public virtual ICollection<tblPresupuestoProyectoInvestigacion> tblPresupuestoProyectoInvestigacion { get; set; }
        public virtual ICollection<tblProblemaInvestigacion> tblProblemaInvestigacion { get; set; }
        public virtual ICollection<tblProblemaProyectoInvestigacion> tblProblemaProyectoInvestigacion { get; set; }
        public virtual ICollection<tblPropagacionGrupo> tblPropagacionGrupo { get; set; }
        public virtual ICollection<tblProyectoInvestigacion> tblProyectoInvestigacion { get; set; }
        public virtual ICollection<tblRecoleccionInformacionProyectoInvestigacion> tblRecoleccionInformacionProyectoInvestigacion { get; set; }
        public virtual ICollection<tblReflexionOnda> tblReflexionOnda { get; set; }
        public virtual ICollection<tblReflexionProyectoInvestigacion> tblReflexionProyectoInvestigacion { get; set; }
        public virtual ICollection<tblSeguimientoProyectoInvestigacion> tblSeguimientoProyectoInvestigacion { get; set; }
    }
}
