//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblIntegrante
    {
        [Display(Name= "Integrante Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]
        public long tblIntegrante_ID { get; set; }
		
        [Display(Name= "Integrante Nombre")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Integrante Nombre es obligatorio")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Integrante Nombre")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]

        public string int_nombre { get; set; }
		
        [Display(Name= "Integrante Apellido")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Integrante Apellido es obligatorio")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Integrante Apellido")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]
        public string int_apellido { get; set; }
		
        [Display(Name= "Integrante Correo")]
        [DataType(DataType.EmailAddress)]
        [EmailAddress(ErrorMessage = "Dirección de mail Inválida")]
        [StringLength(250, ErrorMessage = "Máximo 250 caracteres")]
        public string int_correo { get; set; }
		
        [Display(Name= "Integrante Teléfono")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El teléfono es obligatorio")]
        [DataType(DataType.PhoneNumber)]
        [Phone]
        [RegularExpression(@"^[0-9 ]+$", ErrorMessage = "Formato de teléfono no valido")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]
        public string int_telefono { get; set; }
		
        [Display(Name= "Integrante Cargo")]
        [StringLength(200, ErrorMessage = "Máximo 200 caracteres")]
        public string int_cargo { get; set; }
		
        [Display(Name="Equipo Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Equipo Id es obligatorio")]
        public long tblEquipo_ID { get; set; }
		
    
        public virtual tblEquipo tblEquipo { get; set; }
    }
}
