//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblInvitacionGrupo
    {
        [Display(Name="Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name="Usuario Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Usuario Id es obligatorio")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Usuario Id")]
        [StringLength(128, ErrorMessage = "Máximo 128 caracteres")]
        public string idUsuario { get; set; }
		
        [Display(Name="Grupo Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Grupo Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int idGrupo { get; set; }
		
        [Display(Name="Rol Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Rol Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int idRol { get; set; }
		
        [Display(Name="Aceptada")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Aceptado es obligatorio")]
        public bool Aceptada { get; set; }
		
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tblGrupoInvestigacion tblGrupoInvestigacion { get; set; }
        public virtual tblRol tblRol { get; set; }
    }
}
