//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblIdiomas
    {
        public tblIdiomas()
        {
            this.tblNivelIdioma = new HashSet<tblNivelIdioma>();
        }
    
        [Display(Name= "Idiomas Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Idiomas Id es obligatoria")]
        public long tblIdiomas_ID { get; set; }
		
        [Display(Name= "Idiomas Nombre")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Idiomas Nombre es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Idiomas Nombre")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]

        public string idi_nombre { get; set; }
		
        [Display(Name= "Idiomas Descripción")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Idiomas Descripción es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Idiomas Descripción")]
        [StringLength(255, ErrorMessage = "Máximo 255 caracteres")]

        public string idi_descripcion { get; set; }
		
    
        public virtual ICollection<tblNivelIdioma> tblNivelIdioma { get; set; }
    }
}
