//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblIntegrantesGrupoInv
    {
        [Display(Name= "Integrantes Grupo Inv Id")]
        [Required]
        public long tblIntegrantesGrupoInv_ID { get; set; }
		
        [Display(Name= "Grupos Investigación Id")]
        [Required]
        public long tblGruposInvestigacion_ID { get; set; }
		
        [Display(Name= "Usuario Plataforma Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Usuario Plataforma Id es obligatorio")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Usuario Plataforma Id")]
        [StringLength(128, ErrorMessage = "Máximo 128 caracteres")]

        public string tblUsuarioPlataforma_ID { get; set; }
		
        [Display(Name= "Integrantes Grupo Inv Fecha Vinculación")]
        [Required]
        public System.DateTime intGruInv_fechaVinculacion { get; set; }
		
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tblGruposInvestigacion tblGruposInvestigacion { get; set; }
    }
}
