//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblLineaInvestigacion
    {
        public tblLineaInvestigacion()
        {
            this.tblGrupoInvestigacion = new HashSet<tblGrupoInvestigacion>();
        }
    
        [Display(Name="id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name="Nombre")]
        
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Nombre es obligatorio")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Nombre")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]

        public string Nombre { get; set; }
		
        [Display(Name="Categoria")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Categoria es obligatoria")]
        [Range(0,int.MaxValue)]
		public int Categoria { get; set; }
		
    
        public virtual ICollection<tblGrupoInvestigacion> tblGrupoInvestigacion { get; set; }
    }
}
