//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblLenguas
    {
        public tblLenguas()
        {
            this.tblNivelLengua = new HashSet<tblNivelLengua>();
        }
    
        [Display(Name= "Lenguas Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Lenguas Id es obligatoria")]
        public long tblLenguas_ID { get; set; }
		
        [Display(Name= "Lenguas Nombre")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Lenguas Nombre es obligatorio")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Lenguas Nombre")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]

        public string len_nombre { get; set; }
		
        [Display(Name= "Lenguas Descripción")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Lenguas Descripción")]
        [StringLength(255, ErrorMessage = "Máximo 255 caracteres")]
        public string len_descripcion { get; set; }
		
    
        public virtual ICollection<tblNivelLengua> tblNivelLengua { get; set; }
    }
}
