//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblLogAcceso
    {
        [Display(Name="id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name="Rol")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Rol es obligatorio")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Rol")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]

        public string Rol { get; set; }
		
        [Display(Name="Usuario")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Usuario es obligatorio")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Usuario")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string Usuario { get; set; }
		
        [Display(Name="IP")]
        [StringLength(20, ErrorMessage = "Máximo 20 caracteres")]
		public string IP { get; set; }
		
        [Display(Name="Latitud")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]
        public string Latitud { get; set; }
		
        [Display(Name="Longitud")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]
        public string Longitud { get; set; }
		
        [Display(Name="Altitud")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]
        public string Altitud { get; set; }
		
        [Display(Name="Navegación")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string Navegacion { get; set; }
		
        [Display(Name= "Fecha Inicio Sesión")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FechaInicioSesion { get; set; }
		
        [Display(Name= "Fecha Cierre de Sesión")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FechaCierreSesion { get; set; }
		
    }
}
