//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblMarcoReferenciaProy
    {
        public tblMarcoReferenciaProy()
        {
            this.tblProyectosInvestigacion = new HashSet<tblProyectosInvestigacion>();
        }
    
        [Display(Name= "Marco Referencia Proyecto Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Marco Referencia Proyecto Id es obligatorio")]
        public long tblMarcoReferenciaProy_ID { get; set; }
		
        [Display(Name= "Marco Referencia Proyecto Teórico")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]

        public string marRefProy_marcoTeoricoProy { get; set; }
		
        [Display(Name= "Marco Referencia Proyecto Antecedentes")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string marRefProy_marcoAntecedentesProy { get; set; }
		
        [Display(Name= "Marco Referencia Proyecto Conceptual")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string marRefProy_marcoConceptualProy { get; set; }
		
    
        public virtual ICollection<tblProyectosInvestigacion> tblProyectosInvestigacion { get; set; }
    }
}
