//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblMetodoProy
    {
        public tblMetodoProy()
        {
            this.tblProyectosInvestigacion = new HashSet<tblProyectosInvestigacion>();
        }
    
        [Display(Name= "Método Proyecto Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Método Proyecto Id es obligatorio")]
        public long tblMetodoProy_ID { get; set; }
		
        [Display(Name= "Paradigma Metodológico Id")]
		[Range(0,int.MaxValue)]
		public Nullable<int> tblParadigmaMetodologico_ID { get; set; }
		
        [Display(Name= "Met Proyecto Paradigma Metodológico")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string metProy_paradigmaMetodologicoProy { get; set; }
		
        [Display(Name= "Paradigma Epistemológico Id")]
        [Range(0,int.MaxValue)]
		public Nullable<int> tblParadigmaEpistemologico_ID { get; set; }
		
        [Display(Name= "Tipo Estudio Proyecto Id")]
		[Range(0,int.MaxValue)]
		public Nullable<int> tblTipoEstudioProy_ID { get; set; }
		
        [Display(Name= "Diseño Proyecto ID")]
		[Range(0,int.MaxValue)]
		public Nullable<int> tblDisenioProy_ID { get; set; }
		
        [Display(Name= "Histórico Hermenéutico")]
		[Range(0,int.MaxValue)]
		public Nullable<int> tblHistoricoHermeneutico { get; set; }
		
        [Display(Name= "Critico Social")]
		[Range(0,int.MaxValue)]
		public Nullable<int> tblCriticoSocial { get; set; }
		
        [Display(Name= "Met Proyecto paradigma Epistemológico")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]

        public string metProy_paradigmaEpistemologicoProy { get; set; }
		
        [Display(Name= "Met Proyecto población Muestra")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string metProy_poblacionMuestraProy { get; set; }
		
        [Display(Name= "Met Proyecto técnicas Instrumentos")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string metProy_tecnicasInstrumentosProy { get; set; }
		
        [Display(Name= "Met Proyecto Procedimiento")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string metProy_procedimientoProy { get; set; }
		
        [Display(Name= "Met Proyecto plan Análisis Datos")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string metProy_planAnalisisDatosProy { get; set; }
		
    
        public virtual tblCriticoSocial tblCriticoSocial1 { get; set; }
        public virtual tblDiseniosProy tblDiseniosProy { get; set; }
        public virtual tblHistoricoHermeneutico tblHistoricoHermeneutico1 { get; set; }
        public virtual tblParadigmaEpistemologico tblParadigmaEpistemologico { get; set; }
        public virtual tblParadigmaMetodologico tblParadigmaMetodologico { get; set; }
        public virtual tblTipoEstudioProy tblTipoEstudioProy { get; set; }
        public virtual ICollection<tblProyectosInvestigacion> tblProyectosInvestigacion { get; set; }
    }
}
