//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblMunicipios
    {
        public tblMunicipios()
        {
            this.tblAsesorZona = new HashSet<tblAsesorZona>();
            this.tblInstitucion = new HashSet<tblInstitucion>();
            this.tblMeta = new HashSet<tblMeta>();
        }
    
        [Display(Name= "Municipio Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Municipio Id es obligatorio")]
        [StringLength(5, ErrorMessage = "Máximo 5 caracteres")]
        public string idMunicipio { get; set; }
		
        [Display(Name= "Departamento Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Departamento Id es obligatorio")]
        [StringLength(2, ErrorMessage = "Máximo 2 caracteres")]
        public string idDepartamento { get; set; }
		
        [Display(Name= "Nombre Municipio")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Nombre Municipio es obligatorio")]
        [StringLength(250, ErrorMessage = "Máximo 250 caracteres")]
        public string NombreMunicipio { get; set; }
		
        [Display(Name= "Nombre Departamento")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Nombre Departamento es obligatorio")]
        [StringLength(250, ErrorMessage = "Máximo 250 caracteres")]
        public string NombreDepartamento { get; set; }
		
        [Display(Name= "Región Id")]
		public Nullable<long> tblRegion_ID { get; set; }
		
    
        public virtual ICollection<tblAsesorZona> tblAsesorZona { get; set; }
        public virtual ICollection<tblInstitucion> tblInstitucion { get; set; }
        public virtual ICollection<tblMeta> tblMeta { get; set; }
        public virtual tblRegion tblRegion { get; set; }
    }
}
