//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblMaestroCoInvestigador
    {
        [Display(Name="id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name="Usuario Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Usuario Id es obligatorio")]
        [StringLength(128, ErrorMessage = "Máximo 128 caracteres")]
        public string idUsuario { get; set; }
		
        [Display(Name="Tiempo Ondas")]
		[Range(0,int.MaxValue)]
		public Nullable<int> TiempoOndas { get; set; }
		
        [Display(Name="Pregrado")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El pregrado es obligatorio")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para pregrado")]
        [StringLength(255, ErrorMessage = "Máximo 255 caracteres")]
        public string Pregrado { get; set; }
		
        [Display(Name="Postgrado")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El postgrado es obligatorio")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para postgrado")]
        [StringLength(255, ErrorMessage = "Máximo 255 caracteres")]
        public string Postgrado { get; set; }
		
        [Display(Name="Otro")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Otro es obligatorio")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Otro")]
        [StringLength(255, ErrorMessage = "Máximo 255 caracteres")]
        public string Otro { get; set; }
		
        [Display(Name= "Área Conocimiento Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Área Conocimiento Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int idAreaConocimiento { get; set; }
		
        [Display(Name= "Experiencia Área Conocimiento")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La experiencia Área conocimiento es obligatoria")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string ExperienciaAreaConocimiento { get; set; }
		
        [Display(Name= "Institución Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Institución Id es obligatoria")]
        [Range(0,int.MaxValue)]
		public int idInstitucion { get; set; }
		
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tblAreaConocimiento tblAreaConocimiento { get; set; }
        public virtual tblInstitucion tblInstitucion { get; set; }
    }
}
