//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblMetodoProy_Rev
    {
        public tblMetodoProy_Rev()
        {
            this.tblProyectosInvestigacion_Rev = new HashSet<tblProyectosInvestigacion_Rev>();
        }
    
        [Display(Name= "Método Proyecto Rev Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Método Proyecto Rev Id es obligatorio")]

        public long tblMetodoProy_Rev_ID { get; set; }
		
        [Display(Name= "Método Proyecto paradigma Metodológico")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string metProy_paradigmaMetodologicoProy { get; set; }
		
        [Display(Name= "Método paradigma Epistemológico")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string metProy_paradigmaEpistemologicoProy { get; set; }
		
        [Display(Name= "Método población Muestra")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string metProy_poblacionMuestraProy { get; set; }
		
        [Display(Name= "Método Proyecto técnicas Instrumentos")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string metProy_tecnicasInstrumentosProy { get; set; }
		
        [Display(Name= "Método Proyecto procedimiento")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string metProy_procedimientoProy { get; set; }
		
        [Display(Name= "Método Proyecto plan Análisis Datos")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string metProy_planAnalisisDatosProy { get; set; }
		
    
        public virtual ICollection<tblProyectosInvestigacion_Rev> tblProyectosInvestigacion_Rev { get; set; }
    }
}
