//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblMarcoReferenciaProy_Rev
    {
        public tblMarcoReferenciaProy_Rev()
        {
            this.tblProyectosInvestigacion_Rev = new HashSet<tblProyectosInvestigacion_Rev>();
        }
    
        [Display(Name= "Marco Referencia Proyecto Rev ID")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Paradigma Epistemológico es obligatorio")]

        public long tblMarcoReferenciaProy_Rev_ID { get; set; }
		
        [Display(Name= "Marco Referencia Proyecto Teórico")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Marco Referencia de Proyecto Teórico")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]

        public string marRefProy_marcoTeoricoProy { get; set; }
		
        [Display(Name= "Marco Referencia Proyecto Antecedentes")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Marco Referencia de Proyecto Antecedentes")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string marRefProy_marcoAntecedentesProy { get; set; }
		
        [Display(Name= "Marco Referencia Proyecto Conceptual")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Marco Referencia Proyecto Conceptual")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string marRefProy_marcoConceptualProy { get; set; }
		
    
        public virtual ICollection<tblProyectosInvestigacion_Rev> tblProyectosInvestigacion_Rev { get; set; }
    }
}
