//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblMeta
    {
        [Display(Name= "Meta Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Meta Id es obligatoria")]
        public long tblMeta_ID { get; set; }
		
        [Display(Name= "Meta grupo Investigación Estudiantil")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Meta grupo Investigación Estudiantil es obligatoria")]
        [Range(0,int.MaxValue)]
		public int met_grupoInvestigacionEstudiantil { get; set; }
		
        [Display(Name= "Meta Estudiante Investigado")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Meta Estudiante Investigado es obligatoria")]
        [Range(0,int.MaxValue)]
		public int met_estudianteInvestigando { get; set; }
		
        [Display(Name= "Meta Grupo Investigación Docente")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Meta Grupo Investigación Docente es obligatoria")]
        [Range(0,int.MaxValue)]
		public int met_grupoInvestigacionDocente { get; set; }
		
        [Display(Name= "Meta Docente Investigando")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Meta Docente Investigando es obligatoria")]
        [Range(0,int.MaxValue)]
		public int met_docenteInvestigando { get; set; }
		
        [Display(Name= "Meta Establecimientos Educativos")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Meta Establecimientos Educativos es obligatoria")]
        [Range(0,int.MaxValue)]
		public int met_establecimientosEducativos { get; set; }
		
        [Display(Name= "Meta Padres Formados 40")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Meta Padres Formados 40 es obligatoria")]
        [Range(0,int.MaxValue)]
		public int met_padresFormados40 { get; set; }
		
        [Display(Name= "Meta estudiantes Formados 40")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Meta estudiantes Formados 40 es obligatoria")]
        [Range(0,int.MaxValue)]
		public int met_estudiantesFormados40 { get; set; }
		
        [Display(Name= "Meta Docentes Formados 120")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Meta Docentes Formados 120 es obligatoria")]
        [Range(0,int.MaxValue)]
		public int met_docentesFormados120 { get; set; }
		
        [Display(Name= "Meta Estudiantes Formados 180")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Meta Estudiantes Formados 180 es obligatoria")]
        [Range(0,int.MaxValue)]
		public int met_estudiantesFormados180 { get; set; }
		
        [Display(Name= "Meta Docentes Formados 180")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Meta Docentes Formados 180 es obligatoria")]
        [Range(0,int.MaxValue)]
		public int met_docentesFormados180 { get; set; }
		
        [Display(Name= "Municipio Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Municipio Id es obligatoria")]
        [StringLength(5, ErrorMessage = "Máximo 5 caracteres")]

        public string idMunicipio { get; set; }
		
    
        public virtual tblMunicipios tblMunicipios { get; set; }
    }
}
