//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblNivel
    {
        public tblNivel()
        {
            this.tblNivelIdioma = new HashSet<tblNivelIdioma>();
            this.tblNivelLengua = new HashSet<tblNivelLengua>();
        }
    
        [Display(Name= "Nivel Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Nivel Id es obligatorio")]

        public long tblNivel_ID { get; set; }
		
        [Display(Name= "Nivel nivel")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Nivel nivel es obligatorio")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]
        public string tblNivel_nivel { get; set; }
		
    
        public virtual ICollection<tblNivelIdioma> tblNivelIdioma { get; set; }
        public virtual ICollection<tblNivelLengua> tblNivelLengua { get; set; }
    }
}
