//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblNivelAcademicoEducacionSuperior
    {
        public tblNivelAcademicoEducacionSuperior()
        {
            this.tblTituloEducacionSuperior = new HashSet<tblTituloEducacionSuperior>();
        }
    
        [Display(Name= "Nivel Académico Educación Superior Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Paradigma Epistemológico es obligatorio")]

        public long tblNivelAcademicoEducacionSuperior_ID { get; set; }
		
        [Display(Name= "Nivel Académico Educación Superior Nombre")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para paradigma Epistemológico")]
        [StringLength(255, ErrorMessage = "Máximo 255 caracteres")]
        public string nivAcaEduSup_nombre { get; set; }
		
    
        public virtual ICollection<tblTituloEducacionSuperior> tblTituloEducacionSuperior { get; set; }
    }
}
