//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblNivelLengua
    {
        [Display(Name= "Nivel Lengua Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Nivel Lengua Id es obligatorio")]

        public long tblNivelLengua_ID { get; set; }
		
        [Display(Name= "Hoja Vida Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Hoja Vida Id es obligatorio")]

        public long tblHojaVida_ID { get; set; }
		
        [Display(Name= "Lenguas Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Lenguas Id es obligatorio")]

        public long tblLenguas_ID { get; set; }
		
        [Display(Name= "Nivel Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Nivel Id es obligatorio")]

        public long tblNivel_ID { get; set; }
		
    
        public virtual tblHojaVida tblHojaVida { get; set; }
        public virtual tblLenguas tblLenguas { get; set; }
        public virtual tblNivel tblNivel { get; set; }
    }
}
