//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class tblNoticias
    {
        [Display(Name= "Noticia Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]

        [Range(0,int.MaxValue)]
		public int Noticia_ID { get; set; }
		
        [Display(Name= "Noticia Titular")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Titular es obligatorio")]
        //[RegularExpression(@"^[A-Z a-z0-9ÑñáéíóúÁÉÍÓÚ\\-\\#]+$", ErrorMessage = "Carácter no valido para Titular")]
        [StringLength(80, ErrorMessage = "Máximo 80 caracteres")]

        public string not_titulo { get; set; }
		
        [Display(Name= "Noticia Descripción")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Descripción es obligatoria")]
        [StringLength(160, ErrorMessage = "Máximo 160 caracteres")]

        public string not_descripcion { get; set; }

        [AllowHtml]
        [UIHint("tinymce_full_compressed")]
        [Display(Name= "Noticia contenido")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Contenido es obligatorio")]
        //[RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ.[]()#]+$", ErrorMessage = "Carácter no valido para Contenido")]
        [StringLength(4000, ErrorMessage = "Máximo 4000 caracteres")]

        public string not_contenido { get; set; }
		
        [Display(Name= "Noticia url imagen")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Url imagen es obligatoria")]
        [StringLength(500, ErrorMessage = "Máximo 500 caracteres")]

        public string not_urlimage { get; set; }
		
        [Display(Name= "Noticia pie de foto")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Pie de foto es obligatorio")]
        [StringLength(500, ErrorMessage = "Máximo 500 caracteres")]
        public string not_piedefoto { get; set; }
		
        [Display(Name= "Noticia Fecha")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Fecha es obligatoria")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]

        public System.DateTime not_fecha { get; set; }
		
        [Display(Name= "Noticia Autor")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Autor es obligatorio")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Autor")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]

        public string not_autor { get; set; }
		
        [Display(Name= "Noticia Url Potcast")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]

        public string not_urlpotcast { get; set; }
		
        [Display(Name= "Está Activo")]
		public Nullable<bool> estaActivo { get; set; }
		
    }

}
