//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblPresupuestoProyectoInvestigacion
    {
        [Display(Name="Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]

        [Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name="Grupo Investigación Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Grupo Investigación Id es obligatorio")]

        [Range(0,int.MaxValue)]
		public int idGrupoInvestigacion { get; set; }
		
        [Display(Name="Rubro Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Rubro Id es obligatorio")]

        [Range(0,int.MaxValue)]
		public int idRubro { get; set; }
		
        [Display(Name= "Descripción Gasto")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La descripción Gasto es obligatoria")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para descripción Gasto")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]

        public string DescripcionGasto { get; set; }
		
        [Display(Name="Valor Rubro")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Valor Rubro es obligatorio")]

        [Range(0,double.MaxValue)]
		public double ValorRubro { get; set; }
		
        [Display(Name="Valor Unitario")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Valor Unitario es obligatorio")]

        [Range(0,double.MaxValue)]
		public double ValorUnitario { get; set; }
		
        [Display(Name="Total")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Total es obligatorio")]

        [Range(0,double.MaxValue)]
		public double Total { get; set; }
		
    
        public virtual tblGrupoInvestigacion tblGrupoInvestigacion { get; set; }
        public virtual tblRubro tblRubro { get; set; }
    }
}
