//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblPreguntaProyectoInvestigacion
    {
        [Display(Name="Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]

        [Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name= "Información Uno")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]

        public string InformacionUno { get; set; }
		
        [Display(Name= "Fuente Uno")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string FuenteUno { get; set; }
		
        [Display(Name= "Información Dos")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string InformacionDos { get; set; }
		
        [Display(Name= "Fuente Dos")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string FuenteDos { get; set; }
		
        [Display(Name= "Información Tres")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string InformacionTres { get; set; }
		
        [Display(Name= "Fuente Tres")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string FuenteTres { get; set; }
		
        [Display(Name= "Reflexión")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string Reflexion { get; set; }
		
        [Display(Name= "Concepto Asesor")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string ConceptoAsesor { get; set; }
		
        [Display(Name= "Revisión")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Revisión es obligatoria")]

        public bool Revision { get; set; }
		
        [Display(Name= "Grupo Investigación Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Grupo Investigación Id es obligatorio")]

        [Range(0,int.MaxValue)]
		public int idGrupoInvestigacion { get; set; }
		
    
        public virtual tblGrupoInvestigacion tblGrupoInvestigacion { get; set; }
    }
}
