//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblProblemaInvestigacion
    {
        [Display(Name="Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]

        [Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name="Descripción")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string Descripcion { get; set; }
		
        [Display(Name="Justificación")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string Justificacion { get; set; }
		
        [Display(Name="Grupo Investigación Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Grupo Investigación Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int idGrupoInvestigacion { get; set; }
		
    
        public virtual tblGrupoInvestigacion tblGrupoInvestigacion { get; set; }
    }
}
