//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblProyectosGruposInvstigacion
    {
        [Display(Name="Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]

        public long id { get; set; }
		
        [Display(Name= "Proyectos de investigación Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Proyecto de investigación Id es obligatorio")]

        public long tblProyectosInvestigacion_ID { get; set; }
		
        [Display(Name= "Título Id")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string tituloProy { get; set; }
		
        [Display(Name= "Resumen")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string resumenProy { get; set; }
		
        [Display(Name= "Palabras Claves")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string palabrasClavesProy { get; set; }
		
        [Display(Name= "Eje investigación")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string ejeInvestigacionProy { get; set; }
		
        [Display(Name= "Justificación Eje Inv ")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string justEjeInvProy { get; set; }
		
        [Display(Name= "Problema")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string problemaProy { get; set; }
		
        [Display(Name= "Pregunta")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string preguntaProy { get; set; }
		
        [Display(Name= "Sub-pregunta ")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string subpreguntaProy { get; set; }
		
        [Display(Name= "Justificación")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string justProy { get; set; }
		
        [Display(Name= "Objetivo General")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string objGeneralProy { get; set; }
		
        [Display(Name= "Objetivos Específicos")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string objEspecificosProy { get; set; }
		
        [Display(Name= "Marco Teórico")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string marcoTeoricoProy { get; set; }
		
        [Display(Name= "Marco Antecedentes")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string marcoAntecedentesProy { get; set; }
		
        [Display(Name= "Marco Contextual")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string marcoContextualProy { get; set; }
		
        [Display(Name= "Paradigma Método")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string paradigmaMetodoProy { get; set; }
		
        [Display(Name= "Paradigma Epistemológico")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string paradigmaEpistemProy { get; set; }
		
        [Display(Name= "Tipo Estudio")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string tipoEstudioProy { get; set; }
		
        [Display(Name= "Diseños")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string diseniosProy { get; set; }
		
        [Display(Name= "Histórico Herramienta")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string historicoHermProy { get; set; }
		
        [Display(Name= "Critico Social")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string criticoSocialProy { get; set; }
		
        [Display(Name= "Población")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string poblacionProy { get; set; }
		
        [Display(Name= "Procedimiento")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string procedimientoProy { get; set; }
		
        [Display(Name= "Técnicas Recolección de Información")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string tecnicasRecInfoProy { get; set; }
		
        [Display(Name= "Plan de Datos")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string planDatosProy { get; set; }
		
        [Display(Name= "Resultados")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string resultadosProy { get; set; }
		
        [Display(Name= "Caracterización")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string caracterizacionProy { get; set; }
		
        [Display(Name= "Referencias")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string referenciasProy { get; set; }
		
    
        public virtual tblProyectosInvestigacion tblProyectosInvestigacion { get; set; }
    }
}
