//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblPresentacionProyecto
    {
        public tblPresentacionProyecto()
        {
            this.tblProyectosInvestigacion = new HashSet<tblProyectosInvestigacion>();
        }
    
        [Display(Name= "Presentación Proyecto Id")]
     
        public long tblPresentacionProyecto_ID { get; set; }
		
        [Display(Name= "Presentación Proyecto titulo")]
        
        [StringLength(100, ErrorMessage = "Máximo 100 caracteres")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Título es obligatorio")]
        public string preProy_tituloProy { get; set; }
		
        [Display(Name= "Presentación Proyecto resumen")]
       
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string preProy_resumenProy { get; set; }
		
        [Display(Name= "Presentación Proyecto palabra clave")]
        
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string preProy_palabrasClavesProy { get; set; }
		
        [Display(Name= "Eje Investigación Id")]
		[Range(0,int.MaxValue)]
		public Nullable<int> tblEjeInvestigacion_ID { get; set; }
		
        [Display(Name= "Presentación proyecto eje investigación")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string preProy_ejeInvestigacionProy { get; set; }
		
    
        public virtual tblEjeInvestigacion tblEjeInvestigacion { get; set; }
        public virtual ICollection<tblProyectosInvestigacion> tblProyectosInvestigacion { get; set; }
    }
}
