//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblParadigmaMetodologico
    {
        public tblParadigmaMetodologico()
        {
            this.tblMetodoProy = new HashSet<tblMetodoProy>();
        }
    
        [Display(Name= "Paradigma Metodológico ID")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int tblParadigmaMetodologico_ID { get; set; }
		
        [Display(Name= "Nombre paradigma metodológico")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El paradigma metodológico es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para paradigma metodológico")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]
        public string parMet_nombre { get; set; }
		
    
        public virtual ICollection<tblMetodoProy> tblMetodoProy { get; set; }
    }
}
