//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblProductosContratista
    {
        [Display(Name= "Producto Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Producto Id es obligatorio")]

        [Range(0,int.MaxValue)]
		public int Id_Producto { get; set; }
		
        [Display(Name= "Contratista Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Contratista Id es obligatorio")]
        [StringLength(128, ErrorMessage = "Máximo 128 caracteres")]


        public string Id_Contratista { get; set; }
		
        [Display(Name= "Actividad Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Actividad Id es obligatoria")]
        

        [Range(0,int.MaxValue)]
		public int Id_Actividad { get; set; }
		
        [Display(Name= "Nombre del Producto")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Nombre del Producto es obligatorio")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Nombre del Producto")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]


        public string Nombre_Producto { get; set; }
		
        [Display(Name= "Descripción Producto")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string Descripcion_Producto { get; set; }
		
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tblActividadContratista tblActividadContratista { get; set; }
    }
}
