//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblProyectosInvestigacion_Rev
    {
        public tblProyectosInvestigacion_Rev()
        {
            this.tblProyectosInvestigacion = new HashSet<tblProyectosInvestigacion>();
            this.tblProyectosInvestigacion1 = new HashSet<tblProyectosInvestigacion>();
            this.tblProyectosInvestigacion2 = new HashSet<tblProyectosInvestigacion>();
            this.tblProyectosInvestigacion3 = new HashSet<tblProyectosInvestigacion>();
        }
    
        [Display(Name= "Proyecto Investigación Rev Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Proyecto de Investigación Rev Id es obligatorio")]
        public long tblProyectosInvestigacion_Rev_ID { get; set; }
		
        [Display(Name= "Proyectos Investigación Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Proyecto de Investigación Id es obligatorio")]
        public long tblProyectosInvestigacion_ID { get; set; }
		
        [Display(Name= "Estado Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Estado Id es obligatorio")]
        public long tblEstado_ID { get; set; }
		
        [Display(Name= "Presentación Proyecto Rev Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Presentación Proyecto Rev Id es obligatoria")]
        public long tblPresentacionProyecto_Rev_ID { get; set; }
		
        [Display(Name= "Problema investigación Proyecto Rev Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Problema investigación Proyecto Rev Id es obligatorio")]
        public long tblProblemaInvestigacionProy_Rev_ID { get; set; }
		
        [Display(Name= "Marco Referencia Proyecto Rev Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Marco Referencia Proyecto Rev Id es obligatorio")]
        public long tblMarcoReferenciaProy_Rev_ID { get; set; }
		
        [Display(Name= "Método Proyecto Rev Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Método Proyecto Rev Id es obligatorio")]
        public long tblMetodoProy_Rev_ID { get; set; }
		
        [Display(Name= "Características Proyecto Rev Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Las Características Proyecto Rev Id es obligatorio")]
        public long tblCaracteristicasProy_Rev_ID { get; set; }
		
        [Display(Name= "Cronograma Proyecto Rev Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Cronograma Proyecto Rev Id es obligatorio")]
        public long tblCronogramaProy_Rev_ID { get; set; }
		
        [Display(Name= "Presupuesto Proyecto Rev Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Presupuesto Proyecto Rev Id es obligatorio")]
        public long tblPresupuestoProy_Rev_ID { get; set; }
		
        [Display(Name= "Referencias Proyecto Rev Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Referencias Proyecto Rev Id es obligatorio")]
        public long tblReferenciasProy_Rev_ID { get; set; }
		
        [Display(Name= "Usuario Plataforma Evaluador Id")]
        [StringLength(128, ErrorMessage = "Máximo 128 caracteres")]

        public string tblUsuarioPlataforma_Evaluador_ID { get; set; }
		
        [Display(Name= "Proyecto Inv Rev Fecha Asignación")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> proyInvRev_fechaAsignacion { get; set; }
		
        [Display(Name= "Proyecto Inv Rev Fecha Limite Evaluación")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> proyInvRev_fechaLimiteEvaluacion { get; set; }
		
        [Display(Name= "Proyecto Inv Rev Fecha Ultima Evaluación")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> proyInvRev_fechaUltimaEvaluacion { get; set; }
		
    
        public virtual tblCaracteristicasProy_Rev tblCaracteristicasProy_Rev { get; set; }
        public virtual tblCronogramaProy_Rev tblCronogramaProy_Rev { get; set; }
        public virtual tblEstado tblEstado { get; set; }
        public virtual tblMarcoReferenciaProy_Rev tblMarcoReferenciaProy_Rev { get; set; }
        public virtual tblMetodoProy_Rev tblMetodoProy_Rev { get; set; }
        public virtual tblPresentacionProyecto_Rev tblPresentacionProyecto_Rev { get; set; }
        public virtual tblPresupuestoProy_Rev tblPresupuestoProy_Rev { get; set; }
        public virtual tblProblemaInvestigacionProy_Rev tblProblemaInvestigacionProy_Rev { get; set; }
        public virtual ICollection<tblProyectosInvestigacion> tblProyectosInvestigacion { get; set; }
        public virtual ICollection<tblProyectosInvestigacion> tblProyectosInvestigacion1 { get; set; }
        public virtual ICollection<tblProyectosInvestigacion> tblProyectosInvestigacion2 { get; set; }
        public virtual ICollection<tblProyectosInvestigacion> tblProyectosInvestigacion3 { get; set; }
        public virtual tblReferenciasProy_Rev tblReferenciasProy_Rev { get; set; }
    }
}
