//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblProblemaInvestigacionProy
    {
        public tblProblemaInvestigacionProy()
        {
            this.tblProyectosInvestigacion = new HashSet<tblProyectosInvestigacion>();
        }
    
        [Display(Name= "Problema Investigación Proyecto Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]

        public long tblProblemaInvestigacionProy_ID { get; set; }
		
        [Display(Name= "Problema Investigación Proyecto planteamiento Problema")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]

        public string proInvProy_planteamientoProblemaProy { get; set; }
		
        [Display(Name= "Problema Investigación Proyecto pregunta Investigación ")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string proInvProy_preguntaInvestigacionProy { get; set; }
		
        [Display(Name= "Problema Investigación Proyecto Sub-pregunta Investigación")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string proInvProy_subpreguntaInvestigacionProy { get; set; }
		
        [Display(Name= "Problema Investigación Proyecto justificación")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string proInvProy_justificacionProy { get; set; }
		
        [Display(Name= "Problema Investigación Proyecto Objetivo General")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string proInvProy_objetivoGeneralProy { get; set; }
		
        [Display(Name= "Problema Investigación Proyecto Objetivos Específicos ")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string proInvProy_objetivosEspecificosProy { get; set; }
		
    
        public virtual ICollection<tblProyectosInvestigacion> tblProyectosInvestigacion { get; set; }
    }
}
