//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblProblemaProyectoInvestigacion
    {
        [Display(Name="Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]

        [Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name="Como")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]

        public string Como { get; set; }
		
        [Display(Name= " Reflexión")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string Reflexion { get; set; }
		
        [Display(Name= "Concepto Asesor")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string ConceptoAsesor { get; set; }
		
        [Display(Name="Revisión")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Revisión es obligatoria")]

        public bool Revision { get; set; }
		
        [Display(Name= "Grupo investigación Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Grupo investigación Id es obligatorio")]

        [Range(0,int.MaxValue)]
		public int idGrupoInvestigacion { get; set; }
		
    
        public virtual tblGrupoInvestigacion tblGrupoInvestigacion { get; set; }
    }
}
