//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblPropagacionGrupo
    {
        [Display(Name="Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]
		[Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name= "Grupo investigación Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Grupo investigación Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int idGrupoInvestigacion { get; set; }
		
        [Display(Name= "Tipo Feria Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Tipo Feria Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int idTipoFeria { get; set; }
		
        [Display(Name="Archivo")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Archivo es obligatorio")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Archivo")]
        [StringLength(500, ErrorMessage = "Máximo 500 caracteres")]

        public string Archivo { get; set; }
		
        [Display(Name= "Descripción")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string Descripcion { get; set; }
		
    
        public virtual tblGrupoInvestigacion tblGrupoInvestigacion { get; set; }
        public virtual tblTipoFeria tblTipoFeria { get; set; }
    }
}
