//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblProyectosInvestigacion
    {
        public tblProyectosInvestigacion()
        {
            this.tblProyectosGruposInvstigacion = new HashSet<tblProyectosGruposInvstigacion>();
        }
    
        [Display(Name= "Proyectos de investigación Id")]
        //[Required(AllowEmptyStrings = false, ErrorMessage = "El Proyecto de investigación Id es obligatorio")]
        [Required]
        public long tblProyectosInvestigacion_ID { get; set; }
		
        [Display(Name= "Grupo Investigación Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Grupo Investigación Id es obligatorio")]
        public long tblGruposInvestigacion_ID { get; set; }
		
        [Display(Name= "Estado Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Estado Id es obligatorio")]
        public long tblEstado_ID { get; set; }
		
        [Display(Name= "Presentación Proyecto Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Presentación Proyecto Id es obligatoria")]
        public long tblPresentacionProyecto_ID { get; set; }
		
        [Display(Name= "Problema investigación Proyecto Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Problema investigación Proyecto Id es obligatorio")]
        public long tblProblemaInvestigacionProy_ID { get; set; }
		
        [Display(Name= "Marco Referencia Proyecto Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Paradigma Epistemológico es obligatorio")]
        public long tblMarcoReferenciaProy_ID { get; set; }
		
        [Display(Name= "Método Proyecto Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Marco Referencia Proyecto Id es obligatorio")]
        public long tblMetodoProy_ID { get; set; }
		
        [Display(Name= "Características Proyecto Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Las Características Proyecto Id es obligatorio")]
        public long tblCaracteristicasProy_ID { get; set; }
		
        [Display(Name= "Cronograma Proyecto Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Cronograma Proyecto Id es obligatorio")]
        public long tblCronogramaProy_ID { get; set; }
		
        [Display(Name= "Presupuesto Proyecto Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Presupuesto Proyecto Id es obligatorio")]
        public long tblPresupuestoProy_ID { get; set; }
		
        [Display(Name= "Referencias Proyecto Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Referencia del Proyecto Id es obligatorio")]
        public long tblReferenciasProy_ID { get; set; }
		
        [Display(Name= "Evaluación Proyecto Colciencias Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Evaluación del Proyecto Colciencias Id es obligatorio")]
        public long tblEvaluacionProyColciencias_ID { get; set; }
		
        [Display(Name= "Evaluación Proyecto Investic Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Evaluación Proyecto Investic Id es obligatorio")]
        public long tblEvaluacionProyInvestic_ID { get; set; }
		
        [Display(Name= "Evaluación Proyecto Evaluador1 Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Evaluación del Proyecto Evaluador1 Id es obligatorio")]
        public long tblEvaluacionProyEvaluador1_ID { get; set; }
		
        [Display(Name= "Evaluación Proyecto Evaluador2 Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Evaluación del Proyecto Evaluador2 Id es obligatorio")]
        public long tblEvaluacionProyEvaluador2_ID { get; set; }
		
        [Display(Name= "Proyecto Inv nombre")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Proyecto Inv nombre es obligatorio")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Proyecto Inv nombre")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]

        public string proyInv_nombreProyecto { get; set; }
		
        [Display(Name= "Proyecto Inv fecha Creación")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Proyecto Inv fecha Creación es obligatorio")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime proyInv_fechaCreacion { get; set; }
		
        [Display(Name= "Proyecto Inv fecha Ultima Modificación")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La fecha Ultima Modificación del proyecto es obligatoria")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime proyInv_fechaUltimaModificacion { get; set; }

   
        public virtual tblCaracteristicasProy tblCaracteristicasProy { get; set; }
        public virtual tblCronogramaProy tblCronogramaProy { get; set; }
        public virtual tblEstado tblEstado { get; set; }
        public virtual tblGruposInvestigacion tblGruposInvestigacion { get; set; }
        public virtual tblMarcoReferenciaProy tblMarcoReferenciaProy { get; set; }
        public virtual tblMetodoProy tblMetodoProy { get; set; }
        public virtual tblPresentacionProyecto tblPresentacionProyecto { get; set; }
        public virtual tblPresupuestoProy tblPresupuestoProy { get; set; }
        public virtual tblProblemaInvestigacionProy tblProblemaInvestigacionProy { get; set; }
        public virtual ICollection<tblProyectosGruposInvstigacion> tblProyectosGruposInvstigacion { get; set; }
        public virtual tblProyectosInvestigacion_Rev tblProyectosInvestigacion_Rev { get; set; }
        public virtual tblProyectosInvestigacion_Rev tblProyectosInvestigacion_Rev1 { get; set; }
        public virtual tblProyectosInvestigacion_Rev tblProyectosInvestigacion_Rev2 { get; set; }
        public virtual tblProyectosInvestigacion_Rev tblProyectosInvestigacion_Rev3 { get; set; }
        public virtual tblReferenciasProy tblReferenciasProy { get; set; }
    }
}
