//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblProyectoInvestigacion
    {
        public tblProyectoInvestigacion()
        {
            this.tblAsesorGrupoInvestigacion = new HashSet<tblAsesorGrupoInvestigacion>();
        }
    
        [Display(Name="Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]

        [Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name= "Grupo Investigación Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Grupo Investigación Id es obligatorio")]

        [Range(0,int.MaxValue)]
		public int idGrupoInvestigacion { get; set; }
		
        [Display(Name="Nombre")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Nombre es obligatorio")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Nombre")]
        [StringLength(255, ErrorMessage = "Máximo 255 caracteres")]


        public string Nombre { get; set; }
		
        [Display(Name="Fecha de Inicio")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Fecha de Inicio es obligatorio")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]

        public System.DateTime FechaInicio { get; set; }
		
        [Display(Name="Fecha de Finalización")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Fecha de Finalización es obligatorio")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]

        public System.DateTime FechaFinalizacion { get; set; }
		
    
        public virtual ICollection<tblAsesorGrupoInvestigacion> tblAsesorGrupoInvestigacion { get; set; }
        public virtual tblGrupoInvestigacion tblGrupoInvestigacion { get; set; }
    }
}
