//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblPresentacionProyecto_Rev
    {
        public tblPresentacionProyecto_Rev()
        {
            this.tblProyectosInvestigacion_Rev = new HashSet<tblProyectosInvestigacion_Rev>();
        }
    
        [Display(Name= "Presentación Proyecto Rev Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Presentación Proyecto Rev Id es obligatorio")]

        public long tblPresentacionProyecto_Rev_ID { get; set; }
		
        [Display(Name= "Presentación Proyecto Título")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]

        public string preProy_tituloProy { get; set; }
		
        [Display(Name= "Presentación Proyecto Resumen ")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string preProy_resumenProy { get; set; }
		
        [Display(Name= "Presentación Proyecto palabras Claves")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string preProy_palabrasClavesProy { get; set; }
		
        [Display(Name= "Presentación Proyecto Eje Investigación")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string preProy_ejeInvestigacionProy { get; set; }
		
    
        public virtual ICollection<tblProyectosInvestigacion_Rev> tblProyectosInvestigacion_Rev { get; set; }
    }
}
