//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblRecoleccionInformacionProyectoInvestigacion
    {
        [Display(Name="Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]

        [Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name= "Grupo Investigación Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Grupo Investigación Id es obligatorio")]

        [Range(0,int.MaxValue)]
		public int idGrupoInvestigacion { get; set; }
		
        [Display(Name="Instrumento Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Instrumento Id es obligatorio")]

        [Range(0,int.MaxValue)]
		public int idInstrumento { get; set; }
		
        [Display(Name="Evidencia")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Evidencia es obligatoria")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para la Evidencia")]
        [StringLength(255, ErrorMessage = "Máximo 255 caracteres")]
        public string Evidencia { get; set; }
		
        [Display(Name= "Descripción")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Descripción es obligatoria")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string Descripcion { get; set; }
		
    
        public virtual tblGrupoInvestigacion tblGrupoInvestigacion { get; set; }
        public virtual tblHerramientasRecoleccionInformacion tblHerramientasRecoleccionInformacion { get; set; }
    }
}
