//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblReflexionProyectoInvestigacion
    {
        [Display(Name="Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]

        [Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name="Fecha Inicio")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Fecha Inicio es obligatoria")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]

        public System.DateTime FechaInicio { get; set; }
		
        [Display(Name="Ultima Modificación")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
		
        [Display(Name="Proceso")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]

        public string Proceso { get; set; }
		
        [Display(Name="Motivación")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string Motivacion { get; set; }
		
        [Display(Name="Reflexión")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string Reflexion { get; set; }
		
        [Display(Name="Concepto Asesor")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string ConceptoAsesor { get; set; }
		
        [Display(Name="Revisado")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Revisado es obligatorio")]

        public bool Revisado { get; set; }
		
        [Display(Name= "Grupo investigación Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Grupo investigación Id es obligatorio")]

        [Range(0,int.MaxValue)]
		public int idGrupoInvestigacion { get; set; }
		
    
        public virtual tblGrupoInvestigacion tblGrupoInvestigacion { get; set; }
    }
}
