//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblRegion
    {
        public tblRegion()
        {
            this.tblMunicipios = new HashSet<tblMunicipios>();
        }
    
        [Display(Name="Región Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Región Id es obligatoria")]
        public long tblRegion_ID { get; set; }
		
        [Display(Name= "Región Nombre")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]

        public string reg_nombre { get; set; }
		
    
        public virtual ICollection<tblMunicipios> tblMunicipios { get; set; }
    }
}
