//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblResponsabContratista
    {
        public tblResponsabContratista()
        {
            this.tblActividadContratista = new HashSet<tblActividadContratista>();
            this.tblProgramaTareasContratista = new HashSet<tblProgramaTareasContratista>();
        }
    
        [Display(Name="Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]

        [Range(0,int.MaxValue)]
		public int Id { get; set; }
		
        [Display(Name= "Contratista Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Contratista Id es obligatorio")]
        [StringLength(128, ErrorMessage = "Máximo 128 caracteres")]


        public string Id_Contratista { get; set; }
		
        [Display(Name= "Descripción")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Descripción es obligatoria")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Descripción")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]


        public string Descripcion { get; set; }
		
        [Display(Name= "Coordinador Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Coordinador Id es obligatorio")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Coordinador Id")]
        [StringLength(128, ErrorMessage = "Máximo 128 caracteres")]
        public string Id_Coordinador { get; set; }
		
        [Display(Name= "Consecutivo")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Consecutivo es obligatorio")]

        [Range(0,int.MaxValue)]
		public int Consecutivo { get; set; }
		
        [Display(Name= "Identificador Responsable")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Identificador Responsable es obligatorio")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Identificador Responsable")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]

        public string IdentificadorResponsa { get; set; }
		
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<tblActividadContratista> tblActividadContratista { get; set; }
        public virtual ICollection<tblProgramaTareasContratista> tblProgramaTareasContratista { get; set; }
    }
}
