//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblReferenciasProy_Rev
    {
        public tblReferenciasProy_Rev()
        {
            this.tblProyectosInvestigacion_Rev = new HashSet<tblProyectosInvestigacion_Rev>();
        }
    
        [Display(Name= "Referencias Proyecto Rev Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Referencias Proyecto Rev Id es obligatorio")]

        public long tblReferenciasProy_Rev_ID { get; set; }
		
        [Display(Name= "Referencias del Proyecto")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]

        public string refProy_referencias { get; set; }
		
    
        public virtual ICollection<tblProyectosInvestigacion_Rev> tblProyectosInvestigacion_Rev { get; set; }
    }
}
