//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblRecursosEducativos
    {
        [Display(Name= "Recurso educativo Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]

        [Range(0,int.MaxValue)]
		public int id_rec_educativo { get; set; }
		
        [Display(Name= "Nombre Recurso Educativo")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Nombre es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Caractéres No valido para Nombre")]
        [StringLength(100, ErrorMessage = "Máximo 100 caracteres")]
        public string nom_rec_educativo { get; set; }
		
        [Display(Name= "Descripción Recursos Educativo")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Descripción es obligatoria")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Caractéres No valido para Descripción")]
        [StringLength(100, ErrorMessage = "Máximo 100 caracteres")]
        public string desc_rec_educativo { get; set; }
		
        [Display(Name= "Icono Recursos Educativo")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Icono es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Caractéres No valido para Icono")]
        [StringLength(500, ErrorMessage = "Máximo 500 caracteres")]
        public string icono_rec_educativo { get; set; }
		
        [Display(Name= "Archivo Recurso Educativo")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El archivo es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Caractéres No valido para Archivo")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string archivo_rec_educativo { get; set; }
		
        [Display(Name= "Autor Recurso Educativo")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Autor es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Caractéres No valido para Autor")]
        [StringLength(500, ErrorMessage = "Máximo 500 caracteres")]
        public string autor_rec_educativo { get; set; }
		
        [Display(Name= "Usuario Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Usuario Id es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Caractéres No valido para Autor")]
        [StringLength(128, ErrorMessage = "Máximo 128 caracteres")]
        public string id_user { get; set; }
		
        [Display(Name= "Colección Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Colección Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int id_coleccion { get; set; }
		
    
        public virtual tblColecciones tblColecciones { get; set; }
    }
}
