//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblRubro
    {
        public tblRubro()
        {
            this.tblPresupuestoProyectoInvestigacion = new HashSet<tblPresupuestoProyectoInvestigacion>();
            this.tblRubroPresupuesto = new HashSet<tblRubroPresupuesto>();
        }
    
        [Display(Name="Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name="Rubro")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Rubro es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Rubro")]
        [StringLength(255, ErrorMessage = "Máximo 255 caracteres")]
        public string Rubro { get; set; }
		
        [Display(Name= "Descripción")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string Descripcion { get; set; }
		
    
        public virtual ICollection<tblPresupuestoProyectoInvestigacion> tblPresupuestoProyectoInvestigacion { get; set; }
        public virtual ICollection<tblRubroPresupuesto> tblRubroPresupuesto { get; set; }
    }
}
