//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblReferenciasProy
    {
        public tblReferenciasProy()
        {
            this.tblProyectosInvestigacion = new HashSet<tblProyectosInvestigacion>();
        }
    
        [Display(Name= "Referencias Proyecto Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Referencias Proyecto Id es obligatorio")]

        public long tblReferenciasProy_ID { get; set; }
		
        [Display(Name= "Referencias del Proyecto")]
        [StringLength(255, ErrorMessage = "Máximo 255 caracteres")]

        public string refProy_referencias { get; set; }
		
    
        public virtual ICollection<tblProyectosInvestigacion> tblProyectosInvestigacion { get; set; }
    }
}
