//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblRubroPresupuesto
    {
        [Display(Name= "Rubro Presupuesto Id")]
        //[Required(AllowEmptyStrings = false, ErrorMessage = "El Rubro Presupuesto Id es obligatorio")]
        [Required]
        public long tblRubroPresupuesto_ID { get; set; }
		
        [Display(Name="Presupuesto Proy Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Presupuesto Proy Id es obligatorio")]
        public long tblPresupuestoProy_ID { get; set; }
		
        [Display(Name="Rubro Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Rubro Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int tblRubro_ID { get; set; }
		
        [Display(Name= "Rubro Presupuesto Valor")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Rubro Presupuesto Valor es obligatorio")]
        public long rubPre_valor { get; set; }
		
        [Display(Name= "Rubro Presupuesto Fuente")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Rubro Presupuesto Fuente es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Rubro Presupuesto Fuente")]
        public string rubPre_fuente { get; set; }
		
        [Display(Name= "Rubro Presupuesto Justificación")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Rubro Presupuesto Justificación es obligatorio")]
        [RegularExpression(@"^[a-zA-Z ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Rubro Presupuesto Justificación")]
        public string rubPre_justificacion { get; set; }
		
    
        public virtual tblPresupuestoProy tblPresupuestoProy { get; set; }
        public virtual tblRubro tblRubro { get; set; }
    }
}
