//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblSeguimientoProyectoInvestigacion
    {
        [Display(Name="Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]

        [Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name= "Grupo Investigación Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Grupo Investigación Id es obligatorio")]

        [Range(0,int.MaxValue)]
		public int idGrupoInvestigacion { get; set; }
		
        [Display(Name= "Fecha de Creación")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Fecha de Creación es obligatorio")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]

        public System.DateTime FechaCreacion { get; set; }
		
        [Display(Name="Fecha de Modificación")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FechaModificacion { get; set; }
		
        [Display(Name="Origen")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Origen es obligatorio")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para El Origen")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]


        public string Origen { get; set; }
		
        [Display(Name="Motivación")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Motivación es obligatoria")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para El Origen")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]

        public string Motivacion { get; set; }
		
        [Display(Name="Reflexión")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Reflexión es obligatoria")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para El Origen")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]

        public string Reflexion { get; set; }
		
        [Display(Name="Observación")]
        [StringLength(1000, ErrorMessage = "Máximo 1000 caracteres")]
        public string Observacion { get; set; }
		
    
        public virtual tblGrupoInvestigacion tblGrupoInvestigacion { get; set; }
    }
}
