//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblSedeEducativa
    {
        public tblSedeEducativa()
        {
            this.tblTutorZonaSedeEducativa = new HashSet<tblTutorZonaSedeEducativa>();
        }
    
        [Display(Name= "Sede Educativa Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Sede Educativa Id es obligatoria")]
        public long tblSedeEducativa_ID { get; set; }
		
        [Display(Name= "Sede Educativa Código DANE")]
		[Range(0,int.MaxValue)]
		public Nullable<int> sedEdu_codigoDane { get; set; }
		
        [Display(Name= "Sede Educativa Nombre")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]

        public string sedEdu_nombre { get; set; }
		
        [Display(Name= "Sede Educativa Dirección")]
        [StringLength(255, ErrorMessage = "Máximo 255 caracteres")]

        public string sedEdu_direccion { get; set; }
		
        [Display(Name= "Sede Educativa Teléfono")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]

        public string sedEdu_telefono { get; set; }
		
        [Display(Name= "Institución Educativa Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Institución Educativa Id es obligatoria")]
        [Range(0,int.MaxValue)]
		public int tblInstitucionEducativa_ID { get; set; }
		
    
        public virtual tblInstitucionEducativa tblInstitucionEducativa { get; set; }
        public virtual ICollection<tblTutorZonaSedeEducativa> tblTutorZonaSedeEducativa { get; set; }
    }
}
