//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblTipoFeria
    {
        public tblTipoFeria()
        {
            this.tblPropagacionGrupo = new HashSet<tblPropagacionGrupo>();
        }
    
        [Display(Name="Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Id es obligatorio")]
        [Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name= "Tipo Feria")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Tipo Feria es obligatorio")]
        [RegularExpression(@"^[a-zA-Z0-9 ñáéíóúÁÉÍÓÚÑ]+$", ErrorMessage = "Carácter no valido para Tipo Feria")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]

        public string TipoFeria { get; set; }
		
        [Display(Name="Descripción")]
		public string Descripcion { get; set; }
		
    
        public virtual ICollection<tblPropagacionGrupo> tblPropagacionGrupo { get; set; }
    }
}
