//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblTipoEstablecimiento
    {
        public tblTipoEstablecimiento()
        {
            this.tblInstitucionEducativa = new HashSet<tblInstitucionEducativa>();
        }
    
        [Display(Name= "Tipo Establecimiento Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Tipo Establecimiento Id es obligatorio")]

        public long tblTipoEstablecimiento_ID { get; set; }
		
        [Display(Name= "Tipo Establecimiento Nombre")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]

        public string tipEst_nombre { get; set; }
		
    
        public virtual ICollection<tblInstitucionEducativa> tblInstitucionEducativa { get; set; }
    }
}
