//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tblTutorZonaSedeEducativa
    {
        [Display(Name= "Tutor Zona Sede Educativa Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Tutor Zona Sede Educativa Id es obligatorio")]

        public long tblTutorZonaSedeEducativa_ID { get; set; }
		
        [Display(Name= "Tutor Zona Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "El Tutor Zona Id es obligatorio")]

        public long tblTutorZona_ID { get; set; }
		
        [Display(Name= "Sede Educativa Id")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La Sede Educativa Id es obligatoria")]

        public long tblSedeEducativa_ID { get; set; }
		
    
        public virtual tblSedeEducativa tblSedeEducativa { get; set; }
        public virtual tblTutorZona tblTutorZona { get; set; }
    }
}
