//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tbNetVirtualGroup
    {
        public tbNetVirtualGroup()
        {
            this.tbNetVirtualMessage = new HashSet<tbNetVirtualMessage>();
            this.tbNetVirtualUserGroup = new HashSet<tbNetVirtualUserGroup>();
            this.tbNetVirtualForo = new HashSet<tbNetVirtualForo>();
        }
    
        [Display(Name="id")]
		[Required]
		[Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name="name")]
		public string name { get; set; }
		
        [Display(Name="description")]
		public string description { get; set; }
		
        [Display(Name="photo")]
		[DataType(DataType.Upload)]
		public byte[] photo { get; set; }
		
        [Display(Name="state")]
		[Required]
		public bool state { get; set; }
		
        [Display(Name="JsonMetadata")]
		public string JsonMetadata { get; set; }
		
        [Display(Name="createDate")]
		public Nullable<System.DateTime> createDate { get; set; }
		
    
        public virtual ICollection<tbNetVirtualMessage> tbNetVirtualMessage { get; set; }
        public virtual ICollection<tbNetVirtualUserGroup> tbNetVirtualUserGroup { get; set; }
        public virtual ICollection<tbNetVirtualForo> tbNetVirtualForo { get; set; }
    }
}
