//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tbNetVirtualUser
    {
        public tbNetVirtualUser()
        {
            this.tbNetVirtualResource = new HashSet<tbNetVirtualResource>();
            this.tbNetVirtualUserGroup = new HashSet<tbNetVirtualUserGroup>();
            this.tbNetVirtualForo = new HashSet<tbNetVirtualForo>();
        }
    
        [Display(Name="id")]
		[Required]
		public System.Guid id { get; set; }
		
        [Display(Name="photo")]
		[DataType(DataType.Upload)]
		public byte[] photo { get; set; }
		
        [Display(Name="state")]
		[Required]
		public bool state { get; set; }
		
        [Display(Name="JsonMetadata")]
		public string JsonMetadata { get; set; }
		
    
        public virtual ICollection<tbNetVirtualResource> tbNetVirtualResource { get; set; }
        public virtual ICollection<tbNetVirtualUserGroup> tbNetVirtualUserGroup { get; set; }
        public virtual ICollection<tbNetVirtualForo> tbNetVirtualForo { get; set; }
    }
}
