//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tbNetVirtualUserGroup
    {
        public tbNetVirtualUserGroup()
        {
            this.tbNetVirtualWall = new HashSet<tbNetVirtualWall>();
        }
    
        [Display(Name="id")]
		[Required]
		[Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name="idNetVirtualUser")]
		[Required]
		public System.Guid idNetVirtualUser { get; set; }
		
        [Display(Name="idNetVirtualGroup")]
		[Required]
		[Range(0,int.MaxValue)]
		public int idNetVirtualGroup { get; set; }
		
        [Display(Name="StateUserAceptGroup")]
		[Required]
		[Range(0,int.MaxValue)]
		public int StateUserAceptGroup { get; set; }
		
        [Display(Name="isOwner")]
		[Required]
		public bool isOwner { get; set; }
		
    
        public virtual tbNetVirtualGroup tbNetVirtualGroup { get; set; }
        public virtual tbNetVirtualUser tbNetVirtualUser { get; set; }
        public virtual ICollection<tbNetVirtualWall> tbNetVirtualWall { get; set; }
    }
}
