//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tbNetVirtualCategoryResource
    {
        public tbNetVirtualCategoryResource()
        {
            this.tbNetVirtualResource = new HashSet<tbNetVirtualResource>();
        }
    
        [Display(Name="id")]
		[Required]
		[Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name="name")]
		public string name { get; set; }
		
        [Display(Name="image")]
		[DataType(DataType.Upload)]
		public byte[] image { get; set; }
		
        [Display(Name="JsonMetadata")]
		public string JsonMetadata { get; set; }
		
    
        public virtual ICollection<tbNetVirtualResource> tbNetVirtualResource { get; set; }
    }
}
