//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class tbNetVirtualMessage
    {
        [Display(Name="id")]
		[Required]
		[Range(0,int.MaxValue)]
		public int id { get; set; }
		
        [Display(Name="message")]
		[Required]
		public string message { get; set; }
		
        [Display(Name="idGroup")]
		[Required]
		[Range(0,int.MaxValue)]
		public int idGroup { get; set; }
		
        [Display(Name="dateSend")]
		[Required]
		public System.DateTime dateSend { get; set; }
		
    
        public virtual tbNetVirtualGroup tbNetVirtualGroup { get; set; }
    }
}
