//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsers
    {
        public AspNetUsers()
        {
            this.tblGruposInvestigacion = new HashSet<tblGruposInvestigacion>();
            this.tblHojaVida = new HashSet<tblHojaVida>();
            this.tblIntegrantesGrupoInv = new HashSet<tblIntegrantesGrupoInv>();
            this.AspNetUserClaims = new HashSet<AspNetUserClaims>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogins>();
            this.AspNetUserRoles = new HashSet<AspNetUserRoles>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string SureName { get; set; }
        public string PersonalID { get; set; }
        public int Genre { get; set; }
        public string Address { get; set; }
        public System.DateTime BirthDay { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string LastName { get; set; }
        public string Celular { get; set; }
        public string Cargo { get; set; }
        public string Contrato { get; set; }
        public string Cdp { get; set; }
        public string Equipo { get; set; }
        public Nullable<System.DateTime> Fecha_IniContrato { get; set; }
        public Nullable<System.DateTime> Fecha_FinContrato { get; set; }
        public string Cedula { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
    
        public virtual ICollection<tblGruposInvestigacion> tblGruposInvestigacion { get; set; }
        public virtual ICollection<tblHojaVida> tblHojaVida { get; set; }
        public virtual ICollection<tblIntegrantesGrupoInv> tblIntegrantesGrupoInv { get; set; }
        public virtual ICollection<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual ICollection<AspNetUserRoles> AspNetUserRoles { get; set; }
    }
}
