//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCronogramaProy_Rev
    {
        public tblCronogramaProy_Rev()
        {
            this.tblProyectosInvestigacion_Rev = new HashSet<tblProyectosInvestigacion_Rev>();
        }
    
        public long tblCronogramaProy_Rev_ID { get; set; }
        public string croProy_revision { get; set; }
    
        public virtual ICollection<tblProyectosInvestigacion_Rev> tblProyectosInvestigacion_Rev { get; set; }
    }
}
