//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEventosAcademicos
    {
        public long tblEventosAcademicos_ID { get; set; }
        public string eveaca_tituloEvento { get; set; }
        public string eveaca_evento { get; set; }
        public string eveaca_lugarEvento { get; set; }
        public Nullable<System.DateTime> eveaca_anoTerminacion { get; set; }
        public long tblHojaVida_ID { get; set; }
    
        public virtual tblHojaVida tblHojaVida { get; set; }
    }
}
