//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFechaCronograma
    {
        public long tblFechaCronograma_ID { get; set; }
        public long tblCronogramaProy_ID { get; set; }
        public string cro_Actividad { get; set; }
        public System.DateTime cro_FechaInicio { get; set; }
        public System.DateTime cro_FechaFin { get; set; }
        public string cro_Indicador { get; set; }
    
        public virtual tblCronogramaProy tblCronogramaProy { get; set; }
    }
}
