//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHojaVida
    {
        public tblHojaVida()
        {
            this.tblEventosAcademicos = new HashSet<tblEventosAcademicos>();
            this.tblExperienciaProyectos = new HashSet<tblExperienciaProyectos>();
            this.tblNivelIdioma = new HashSet<tblNivelIdioma>();
            this.tblNivelLengua = new HashSet<tblNivelLengua>();
            this.tblProductosAcademicos = new HashSet<tblProductosAcademicos>();
            this.tblTituloEducacionSuperior = new HashSet<tblTituloEducacionSuperior>();
        }
    
        public long tblHojaVida_ID { get; set; }
        public Nullable<System.DateTime> hojVid_anoGradoSecundaria { get; set; }
        public string hojVid_tituloSecundaria { get; set; }
        public string tblUsuarioPlataforma_ID { get; set; }
        public Nullable<int> hojVid_Institucion_ID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<tblEventosAcademicos> tblEventosAcademicos { get; set; }
        public virtual ICollection<tblExperienciaProyectos> tblExperienciaProyectos { get; set; }
        public virtual tblInstitucion tblInstitucion { get; set; }
        public virtual ICollection<tblNivelIdioma> tblNivelIdioma { get; set; }
        public virtual ICollection<tblNivelLengua> tblNivelLengua { get; set; }
        public virtual ICollection<tblProductosAcademicos> tblProductosAcademicos { get; set; }
        public virtual ICollection<tblTituloEducacionSuperior> tblTituloEducacionSuperior { get; set; }
    }
}
