//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIdiomas
    {
        public tblIdiomas()
        {
            this.tblNivelIdioma = new HashSet<tblNivelIdioma>();
        }
    
        public long tblIdiomas_ID { get; set; }
        public string idi_nombre { get; set; }
        public string idi_descripcion { get; set; }
    
        public virtual ICollection<tblNivelIdioma> tblNivelIdioma { get; set; }
    }
}
