//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIntegrantesGrupoInv
    {
        public long tblIntegrantesGrupoInv_ID { get; set; }
        public long tblGruposInvestigacion_ID { get; set; }
        public string tblUsuarioPlataforma_ID { get; set; }
        public System.DateTime intGruInv_fechaVinculacion { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tblGruposInvestigacion tblGruposInvestigacion { get; set; }
    }
}
