//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNivelAcademicoEducacionSuperior
    {
        public tblNivelAcademicoEducacionSuperior()
        {
            this.tblTituloEducacionSuperior = new HashSet<tblTituloEducacionSuperior>();
        }
    
        public long tblNivelAcademicoEducacionSuperior_ID { get; set; }
        public string nivAcaEduSup_nombre { get; set; }
    
        public virtual ICollection<tblTituloEducacionSuperior> tblTituloEducacionSuperior { get; set; }
    }
}
