//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNivelIdioma
    {
        public long tblNivelIdioma_ID { get; set; }
        public long tblHojaVida_ID { get; set; }
        public long tblIdiomas_ID { get; set; }
        public long tblNivel_ID { get; set; }
    
        public virtual tblHojaVida tblHojaVida { get; set; }
        public virtual tblIdiomas tblIdiomas { get; set; }
        public virtual tblNivel tblNivel { get; set; }
    }
}
