//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParadigmaMetodologico
    {
        public tblParadigmaMetodologico()
        {
            this.tblMetodoProy = new HashSet<tblMetodoProy>();
        }
    
        public int tblParadigmaMetodologico_ID { get; set; }
        public string parMet_nombre { get; set; }
    
        public virtual ICollection<tblMetodoProy> tblMetodoProy { get; set; }
    }
}
