//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPresupuestoProy
    {
        public tblPresupuestoProy()
        {
            this.tblProyectosInvestigacion = new HashSet<tblProyectosInvestigacion>();
        }
    
        public long tblPresupuestoProy_ID { get; set; }
        public long pre_financiacionInvestic { get; set; }
        public long pre_totatInvestic { get; set; }
        public long pre_totalOtraFuente { get; set; }
        public long pre_total { get; set; }
    
        public virtual ICollection<tblProyectosInvestigacion> tblProyectosInvestigacion { get; set; }
    }
}
