//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPresentacionProyecto
    {
        public tblPresentacionProyecto()
        {
            this.tblProyectosInvestigacion = new HashSet<tblProyectosInvestigacion>();
        }
    
        public long tblPresentacionProyecto_ID { get; set; }
        public string preProy_tituloProy { get; set; }
        public string preProy_resumenProy { get; set; }
        public string preProy_palabrasClavesProy { get; set; }
        public Nullable<int> tblEjeInvestigacion_ID { get; set; }
        public string preProy_ejeInvestigacionProy { get; set; }
    
        public virtual tblEjeInvestigacion tblEjeInvestigacion { get; set; }
        public virtual ICollection<tblProyectosInvestigacion> tblProyectosInvestigacion { get; set; }
    }
}
