//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProyectosInvestigacion
    {
        public long tblProyectosInvestigacion_ID { get; set; }
        public long tblGruposInvestigacion_ID { get; set; }
        public long tblEstado_ID { get; set; }
        public long tblPresentacionProyecto_ID { get; set; }
        public long tblProblemaInvestigacionProy_ID { get; set; }
        public long tblMarcoReferenciaProy_ID { get; set; }
        public long tblMetodoProy_ID { get; set; }
        public long tblCaracteristicasProy_ID { get; set; }
        public long tblCronogramaProy_ID { get; set; }
        public long tblPresupuestoProy_ID { get; set; }
        public long tblReferenciasProy_ID { get; set; }
        public long tblEvaluacionProyColciencias_ID { get; set; }
        public long tblEvaluacionProyInvestic_ID { get; set; }
        public long tblEvaluacionProyEvaluador1_ID { get; set; }
        public long tblEvaluacionProyEvaluador2_ID { get; set; }
        public string proyInv_nombreProyecto { get; set; }
        public System.DateTime proyInv_fechaCreacion { get; set; }
        public System.DateTime proyInv_fechaUltimaModificacion { get; set; }
    
        public virtual tblCaracteristicasProy tblCaracteristicasProy { get; set; }
        public virtual tblCronogramaProy tblCronogramaProy { get; set; }
        public virtual tblEstado tblEstado { get; set; }
        public virtual tblGruposInvestigacion tblGruposInvestigacion { get; set; }
        public virtual tblMarcoReferenciaProy tblMarcoReferenciaProy { get; set; }
        public virtual tblMetodoProy tblMetodoProy { get; set; }
        public virtual tblPresentacionProyecto tblPresentacionProyecto { get; set; }
        public virtual tblPresupuestoProy tblPresupuestoProy { get; set; }
        public virtual tblProblemaInvestigacionProy tblProblemaInvestigacionProy { get; set; }
        public virtual tblProyectosInvestigacion_Rev tblProyectosInvestigacion_Rev { get; set; }
        public virtual tblProyectosInvestigacion_Rev tblProyectosInvestigacion_Rev1 { get; set; }
        public virtual tblProyectosInvestigacion_Rev tblProyectosInvestigacion_Rev2 { get; set; }
        public virtual tblProyectosInvestigacion_Rev tblProyectosInvestigacion_Rev3 { get; set; }
        public virtual tblReferenciasProy tblReferenciasProy { get; set; }
    }
}
