//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPresentacionProyecto_Rev
    {
        public tblPresentacionProyecto_Rev()
        {
            this.tblProyectosInvestigacion_Rev = new HashSet<tblProyectosInvestigacion_Rev>();
        }
    
        public long tblPresentacionProyecto_Rev_ID { get; set; }
        public string preProy_tituloProy { get; set; }
        public string preProy_resumenProy { get; set; }
        public string preProy_palabrasClavesProy { get; set; }
        public string preProy_ejeInvestigacionProy { get; set; }
    
        public virtual ICollection<tblProyectosInvestigacion_Rev> tblProyectosInvestigacion_Rev { get; set; }
    }
}
