//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProblemaInvestigacionProy
    {
        public tblProblemaInvestigacionProy()
        {
            this.tblProyectosInvestigacion = new HashSet<tblProyectosInvestigacion>();
        }
    
        public long tblProblemaInvestigacionProy_ID { get; set; }
        public string proInvProy_planteamientoProblemaProy { get; set; }
        public string proInvProy_preguntaInvestigacionProy { get; set; }
        public string proInvProy_subpreguntaInvestigacionProy { get; set; }
        public string proInvProy_justificacionProy { get; set; }
        public string proInvProy_objetivoGeneralProy { get; set; }
        public string proInvProy_objetivosEspecificosProy { get; set; }
    
        public virtual ICollection<tblProyectosInvestigacion> tblProyectosInvestigacion { get; set; }
    }
}
