//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAI.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRubroPresupuesto
    {
        public long tblRubroPresupuesto_ID { get; set; }
        public long tblPresupuestoProy_ID { get; set; }
        public long tblRubro_ID { get; set; }
        public long rubPre_valor { get; set; }
        public string rubPre_fuente { get; set; }
        public string rubPre_justificacion { get; set; }
    }
}
