//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEG.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class actividade
    {
        public actividade()
        {
            this.evidencias = new HashSet<evidencia>();
            this.productos = new HashSet<producto>();
        }
    
        public int Id_Actividad { get; set; }
        public System.DateTime Fecha_Ini { get; set; }
        public System.DateTime Fecha_Fin { get; set; }
        public string Id_Contratista { get; set; }
        public int Id_Alternativa { get; set; }
        public int Des_Resp_Contratista { get; set; }
        public string Des_Actividad { get; set; }
        public int Id_Estado { get; set; }
        public string Des_Observaciones { get; set; }
        public Nullable<int> Periodo_Reporte { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<evidencia> evidencias { get; set; }
        public virtual ICollection<producto> productos { get; set; }
        public virtual responsabilidade responsabilidade { get; set; }
        public virtual tabla_alternativas tabla_alternativas { get; set; }
        public virtual tabla_estados tabla_estados { get; set; }
    }
}
