//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEG.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.evidencias = new HashSet<evidencia>();
            this.productos = new HashSet<producto>();
            this.AspNetRoles = new HashSet<AspNetRole>();
            this.equipos = new HashSet<equipos>();
            this.programa_tareas = new HashSet<programa_tareas>();
            this.responsabilidades = new HashSet<responsabilidade>();
            this.actividades = new HashSet<actividade>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string Email { get; set; }
        public Nullable<bool> ConfirmedEmail { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public int FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string Cedula { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Celular { get; set; }
        public string Cargo { get; set; }
        public string Contrato { get; set; }
        public string Cdp { get; set; }
        public string Equipo { get; set; }
        public Nullable<System.DateTime> Fecha_IniContrato { get; set; }
        public Nullable<System.DateTime> Fecha_FinContrato { get; set; }
    
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<evidencia> evidencias { get; set; }
        public virtual ICollection<producto> productos { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
        public virtual ICollection<equipos> equipos { get; set; }
        public virtual ICollection<programa_tareas> programa_tareas { get; set; }
        public virtual ICollection<responsabilidade> responsabilidades { get; set; }
        public virtual ICollection<actividade> actividades { get; set; }
    }
}
