//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEG.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class cargo
    {
        public int Id_Cargo { get; set; }
        public string Nombre_Cargo { get; set; }
    }
}
