//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEG.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipos
    {
        public int Id_Equipo { get; set; }
        public string Nombre_Equipo { get; set; }
        public string Id_Coordinador { get; set; }
        public string Nombre_Coordinador { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
