//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEG.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class fechasreporte
    {
        public int Id_SemanaTrabajo { get; set; }
        public System.DateTime Fecha_Ini { get; set; }
        public System.DateTime Fecha_Fin { get; set; }
        public int Activa { get; set; }
    }
}
