//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEG.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int Id_Producto { get; set; }
        public string Id_Contratista { get; set; }
        public int Id_Actividad { get; set; }
        public string Nombre_Producto { get; set; }
        public string Descripcion_Producto { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual actividade actividade { get; set; }
    }
}
