//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEG.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class programa_tareas
    {
        public int Id { get; set; }
        public string Id_Contratista { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int Alternativa { get; set; }
        public int Responsabilidad { get; set; }
        public System.DateTime Fecha_Ini { get; set; }
        public System.DateTime Fecha_Fin { get; set; }
        public int Estado { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual tabla_alternativas tabla_alternativas { get; set; }
        public virtual responsabilidade responsabilidade { get; set; }
    }
}
