//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEG.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class responsabilidade
    {
        public responsabilidade()
        {
            this.programa_tareas = new HashSet<programa_tareas>();
            this.actividades = new HashSet<actividade>();
        }
    
        public int Id { get; set; }
        public string Id_Contratista { get; set; }
        public string Descripcion { get; set; }
        public string Id_Coordinador { get; set; }
        public string IdentificadorResponsa { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<programa_tareas> programa_tareas { get; set; }
        public virtual ICollection<actividade> actividades { get; set; }
    }
}
