//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEG.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_alternativas
    {
        public tabla_alternativas()
        {
            this.programa_tareas = new HashSet<programa_tareas>();
            this.actividades = new HashSet<actividade>();
        }
    
        public int Id_Alternativa { get; set; }
        public string Des_Alternativa { get; set; }
    
        public virtual ICollection<programa_tareas> programa_tareas { get; set; }
        public virtual ICollection<actividade> actividades { get; set; }
    }
}
