//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEG.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla_estados
    {
        public tabla_estados()
        {
            this.actividades = new HashSet<actividade>();
        }
    
        public int Id_Estado { get; set; }
        public string Des_Estado { get; set; }
    
        public virtual ICollection<actividade> actividades { get; set; }
    }
}
