//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEP.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAsesor
    {
        public tblAsesor()
        {
            this.tblAsesorGrupoInvestigacion = new HashSet<tblAsesorGrupoInvestigacion>();
        }
    
        public int id { get; set; }
        public string idUser { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<tblAsesorGrupoInvestigacion> tblAsesorGrupoInvestigacion { get; set; }
    }
}
