//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEP.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAsesorGrupoInvestigacion
    {
        public int id { get; set; }
        public int idProyectoInvestigacion { get; set; }
        public int idAsesor { get; set; }
    
        public virtual tblAsesor tblAsesor { get; set; }
        public virtual tblProyectoInvestigacion tblProyectoInvestigacion { get; set; }
    }
}
