//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEP.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConceptosEstadoArte
    {
        public int id { get; set; }
        public int idEstadoArte { get; set; }
        public string Autor { get; set; }
        public int Publicacion { get; set; }
        public string Texto { get; set; }
    
        public virtual tblEstadoArteProyectoInvestigacion tblEstadoArteProyectoInvestigacion { get; set; }
    }
}
