//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEP.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEstadoArteProyectoInvestigacion
    {
        public tblEstadoArteProyectoInvestigacion()
        {
            this.tblConceptosEstadoArte = new HashSet<tblConceptosEstadoArte>();
        }
    
        public int id { get; set; }
        public int idGrupoInvestigacion { get; set; }
        public string TemaInvestigacion { get; set; }
        public string MapaConceptual { get; set; }
    
        public virtual ICollection<tblConceptosEstadoArte> tblConceptosEstadoArte { get; set; }
        public virtual tblGrupoInvestigacion tblGrupoInvestigacion { get; set; }
    }
}
