//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEP.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblForoProyectoInvestigacion
    {
        public tblForoProyectoInvestigacion()
        {
            this.tblForoProyectoInvestigacion1 = new HashSet<tblForoProyectoInvestigacion>();
        }
    
        public int id { get; set; }
        public string idUser { get; set; }
        public int idGrupoInvestigacion { get; set; }
        public string Titulo { get; set; }
        public string Mensaje { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Respuestas { get; set; }
        public Nullable<int> idForo { get; set; }
        public Nullable<System.DateTime> FechaUltimaRespuesta { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<tblForoProyectoInvestigacion> tblForoProyectoInvestigacion1 { get; set; }
        public virtual tblForoProyectoInvestigacion tblForoProyectoInvestigacion2 { get; set; }
        public virtual tblGrupoInvestigacion tblGrupoInvestigacion { get; set; }
    }
}
