//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEP.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGrupoInvestigacion
    {
        public tblGrupoInvestigacion()
        {
            this.tblCoInvestigadorGrupoInvestigacion = new HashSet<tblCoInvestigadorGrupoInvestigacion>();
            this.tblDocumentosSoporte = new HashSet<tblDocumentosSoporte>();
            this.tblPreguntaInvestigacion = new HashSet<tblPreguntaInvestigacion>();
            this.tblInvitacionGrupo = new HashSet<tblInvitacionGrupo>();
            this.tblMiembroGrupo = new HashSet<tblMiembroGrupo>();
            this.tblPreguntaProyectoInvestigacion = new HashSet<tblPreguntaProyectoInvestigacion>();
            this.tblProblemaInvestigacion = new HashSet<tblProblemaInvestigacion>();
            this.tblProblemaProyectoInvestigacion = new HashSet<tblProblemaProyectoInvestigacion>();
            this.tblProyectoInvestigacion = new HashSet<tblProyectoInvestigacion>();
            this.tblSeguimientoProyectoInvestigacion = new HashSet<tblSeguimientoProyectoInvestigacion>();
            this.tblLecturaAnalisisFuentesinformacionPoryectoInvestigacion = new HashSet<tblLecturaAnalisisFuentesinformacionPoryectoInvestigacion>();
            this.tblPresupuestoProyectoInvestigacion = new HashSet<tblPresupuestoProyectoInvestigacion>();
            this.tblRecoleccionInformacionProyectoInvestigacion = new HashSet<tblRecoleccionInformacionProyectoInvestigacion>();
            this.tblEstadoArteProyectoInvestigacion = new HashSet<tblEstadoArteProyectoInvestigacion>();
            this.tblForoProyectoInvestigacion = new HashSet<tblForoProyectoInvestigacion>();
            this.tblReflexionProyectoInvestigacion = new HashSet<tblReflexionProyectoInvestigacion>();
            this.tblComentarioGrupo = new HashSet<tblComentarioGrupo>();
            this.tblPropagacionGrupo = new HashSet<tblPropagacionGrupo>();
        }
    
        public int id { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int TipoGrupo { get; set; }
        public string Avatar { get; set; }
        public int idInstitucion { get; set; }
        public int idLineaInvestigacion { get; set; }
        public string idUsuario { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<tblCoInvestigadorGrupoInvestigacion> tblCoInvestigadorGrupoInvestigacion { get; set; }
        public virtual ICollection<tblDocumentosSoporte> tblDocumentosSoporte { get; set; }
        public virtual tblInstitucion tblInstitucion { get; set; }
        public virtual tblLineaInvestigacion tblLineaInvestigacion { get; set; }
        public virtual ICollection<tblPreguntaInvestigacion> tblPreguntaInvestigacion { get; set; }
        public virtual ICollection<tblInvitacionGrupo> tblInvitacionGrupo { get; set; }
        public virtual ICollection<tblMiembroGrupo> tblMiembroGrupo { get; set; }
        public virtual ICollection<tblPreguntaProyectoInvestigacion> tblPreguntaProyectoInvestigacion { get; set; }
        public virtual ICollection<tblProblemaInvestigacion> tblProblemaInvestigacion { get; set; }
        public virtual ICollection<tblProblemaProyectoInvestigacion> tblProblemaProyectoInvestigacion { get; set; }
        public virtual ICollection<tblProyectoInvestigacion> tblProyectoInvestigacion { get; set; }
        public virtual ICollection<tblSeguimientoProyectoInvestigacion> tblSeguimientoProyectoInvestigacion { get; set; }
        public virtual ICollection<tblLecturaAnalisisFuentesinformacionPoryectoInvestigacion> tblLecturaAnalisisFuentesinformacionPoryectoInvestigacion { get; set; }
        public virtual ICollection<tblPresupuestoProyectoInvestigacion> tblPresupuestoProyectoInvestigacion { get; set; }
        public virtual ICollection<tblRecoleccionInformacionProyectoInvestigacion> tblRecoleccionInformacionProyectoInvestigacion { get; set; }
        public virtual ICollection<tblEstadoArteProyectoInvestigacion> tblEstadoArteProyectoInvestigacion { get; set; }
        public virtual ICollection<tblForoProyectoInvestigacion> tblForoProyectoInvestigacion { get; set; }
        public virtual ICollection<tblReflexionProyectoInvestigacion> tblReflexionProyectoInvestigacion { get; set; }
        public virtual ICollection<tblComentarioGrupo> tblComentarioGrupo { get; set; }
        public virtual ICollection<tblPropagacionGrupo> tblPropagacionGrupo { get; set; }
    }
}
