//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEP.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvitacionGrupo
    {
        public int id { get; set; }
        public string idUsuario { get; set; }
        public int idGrupo { get; set; }
        public int idRol { get; set; }
        public bool Aceptada { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tblGrupoInvestigacion tblGrupoInvestigacion { get; set; }
        public virtual tblRol tblRol { get; set; }
    }
}
