//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEP.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPresupuestoProyectoInvestigacion
    {
        public int id { get; set; }
        public int idGrupoInvestigacion { get; set; }
        public int idRubro { get; set; }
        public string DescripcionGasto { get; set; }
        public double ValorRubro { get; set; }
        public double ValorUnitario { get; set; }
        public double Total { get; set; }
    
        public virtual tblGrupoInvestigacion tblGrupoInvestigacion { get; set; }
        public virtual tblRubro tblRubro { get; set; }
    }
}
