//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEP.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRol
    {
        public tblRol()
        {
            this.tblInvitacionGrupo = new HashSet<tblInvitacionGrupo>();
            this.tblMiembroGrupo = new HashSet<tblMiembroGrupo>();
        }
    
        public int id { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<tblInvitacionGrupo> tblInvitacionGrupo { get; set; }
        public virtual ICollection<tblMiembroGrupo> tblMiembroGrupo { get; set; }
    }
}
