//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEP.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReflexionProyectoInvestigacion
    {
        public int id { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public string Proceso { get; set; }
        public string Motivacion { get; set; }
        public string Reflexion { get; set; }
        public string ConceptoAsesor { get; set; }
        public bool Revisado { get; set; }
        public int idGrupoInvestigacion { get; set; }
    
        public virtual tblGrupoInvestigacion tblGrupoInvestigacion { get; set; }
    }
}
