//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEP.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRubro
    {
        public tblRubro()
        {
            this.tblPresupuestoProyectoInvestigacion = new HashSet<tblPresupuestoProyectoInvestigacion>();
        }
    
        public int id { get; set; }
        public string Rubro { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<tblPresupuestoProyectoInvestigacion> tblPresupuestoProyectoInvestigacion { get; set; }
    }
}
