//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEP.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRecoleccionInformacionProyectoInvestigacion
    {
        public int id { get; set; }
        public int idGrupoInvestigacion { get; set; }
        public int idInstrumento { get; set; }
        public string Evidencia { get; set; }
        public string Descripcion { get; set; }
    
        public virtual tblGrupoInvestigacion tblGrupoInvestigacion { get; set; }
        public virtual tblHerramientasRecoleccionInformacion tblHerramientasRecoleccionInformacion { get; set; }
    }
}
