//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IEP.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTipoFeria
    {
        public tblTipoFeria()
        {
            this.tblPropagacionGrupo = new HashSet<tblPropagacionGrupo>();
        }
    
        public int id { get; set; }
        public string TipoFeria { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<tblPropagacionGrupo> tblPropagacionGrupo { get; set; }
    }
}
